### ISSUE TITLE
Feature request: log and chart elevation for drives

### ISSUE THREAD

**Issue by olexs** [adriankumpf/teslamate#109]
Changes in elevation have a significant impact on efficiency when driving. The data should already be present in vehicle's position information. Having a summed elevation change (+/- X m) in the "Drives" table as well as an elevation chart in drive details can help evaluate consumption and efficiency in more detail.

**Comment by adriankumpf** [comment]
Yep, that would be an awesome feature. I've already planned to implement that next. It's not as simple as reading the position from the API though since elevation data is not available (anymore): https://tesla-api.timdorr.com/vehicle/state/drivestate

To protect the users privacy, fetching the elevation of every single position from an external maps provider is not an option, in my opinion. My current plan is to rewrite [this library](https://github.com/tkrajina/srtm.py) in Elixir first. That is going to take a while.

**Comment by adriankumpf** [comment]
Resolved by 1e6d71d83455ba44b39a4ab36acc49550e4acc04
