### ISSUE TITLE
Null shift_state published via MQTT

### ISSUE THREAD

**Issue by tohojo** [adriankumpf/teslamate#1158]
I noticed that Teslamate is intermittently reporting a null shift_state via MQTT:

```
Client mosq-4HVU4zyo8u049OF7QP received PUBLISH (d0, q0, r0, m0, 'teslamate/cars/1/shift_state', ... (0 bytes))
Client mosq-4HVU4zyo8u049OF7QP received PUBLISH (d0, q0, r0, m0, 'teslamate/cars/1/inside_temp', ... (4 bytes))
18.7
Client mosq-4HVU4zyo8u049OF7QP received PUBLISH (d0, q0, r0, m0, 'teslamate/cars/1/charge_energy_added', ... (5 bytes))
15.18
Client mosq-4HVU4zyo8u049OF7QP received PUBLISH (d0, q0, r0, m0, 'teslamate/cars/1/geofence', ... (4 bytes))
Home
Client mosq-4HVU4zyo8u049OF7QP received PUBLISH (d0, q0, r0, m0, 'teslamate/cars/1/charger_voltage', ... (3 bytes))
232
Client mosq-4HVU4zyo8u049OF7QP received PUBLISH (d0, q0, r0, m0, 'teslamate/cars/1/rated_battery_range_km', ... (6 bytes))
244.54
Client mosq-4HVU4zyo8u049OF7QP received PUBLISH (d0, q0, r0, m0, 'teslamate/cars/1/shift_state', ... (1 bytes))
P
```
first and second line - with a few seconds in between. This seems to happen repeatedly, and I find it a bit odd? I don't mind the duplicate notifications *with* data (the consumer can just filter those), but the null-data gives some really weird history data, so just suppressing those would be better, I think...

**Comment by adriankumpf** [comment]
This is by design. It basically reflects what the Tesla API reports. At a certain point `null` is reported as `shitft_state`.

Say the shift state was "D" and you drive into an underground garage with poor reception. The car will then eventually fall asleep and the `shift_state` will become `null`.  If `null` values were not published, the shift state would appear to be "D" for the entire time the car is parked.

**Comment by tohojo** [comment]
Hmm, yeah, okay, I can see why changing this may not be obviously better... Fair enough, I'll handle this on the consumer side :)
