### ISSUE TITLE
Comparision with TeslaLogger

### ISSUE THREAD

**Issue by ghostreader86** [adriankumpf/teslamate#120]
I stumpled across [TeslaLogger](https://github.com/bassmaster187/TeslaLogger/tree/master/TeslaLogger) and then across TeslaMate. You wrote TeslaLogger was an inspiration t the beginning. Can you specify what is the difference beside of the programming language?

Thanks in advance.

**Comment by adriankumpf** [comment]
Yeah, sure. First of all there were a couple of reasons for me to start my own logger.

* Tech Stack: I'm personally not a big fan of PHP, MySQL and C#
* I wanted / needed to run the logger with Docker. I tried with to build my own Dockerfiles for TeslaLogger but failed (this was a few month ago).
* I noticed that TeslaLogger had no test coverage which just didn't felt right to me
* I wanted to have a  single instance of the logger to poll multiple cars. That's just not possible with TeslaLogger and won't be with its current database schema.

Those reasons were enough for me to start building TeslaMate. Since then I didn't pay that much attention to TeslaLogger and all its features. But I'll try to name a few differences off the top of my head: 

* Support for many platforms besides the raspberry pi
* No need of a centralized server to wake up / suspend the logger (that's how TeslaLogger does it IIRC). Everything can be self-hosted & no data is shared with me or any other third-party
* Quick & simple setup (depends on previous knowledge on docker etc, of course)
* Clean & mobile friendly web interface which allows to create geo fences and to update settings
* Calculation of consumption (net / gross) values
* a couple of new dashboards / lots of small-ish modifications to the others
* upcoming: privacy-friendly way to add elevation data 
* Thanks to the many people using TeslaMate lots of edge cases are already handled and I'm sure there are quite a few more that will be resolved in the future.
* ... and more things like software architectural / design stuff

**Comment by ChrisPrefect** [comment]
How has this comparison changed over the past 1.5 years? I am just deciding which project I should implement. Thanks! :-)

**Comment by DrMichael** [comment]
For me I'd say

_For TeslaMate:_
C# running with mono under Unix is not ideal (well, Elixir is a bit of an exotic language...)
Everything is in docker
All data is kept in the database, nothing in the (host) filesystem
No centralised server necessary

_For TeslaLogger:_
ScanMyTesla support
Fleet data available

**Comment by Jagganaut** [comment]
That's my perspective  ...
I talked to adrian personally in Berlin in the beginning to understand why he had branched of ... and created  
something 1:1 in elixir ... and i was missing at some point last year the reminder where his "TM" idea was originally coming from.

i openly discussed with adrian why it seemed completely insane from my user perspective to first purchase a
NAS and than besides that to implement by-hand a docker on it for a tesla car. This is above the config capabilities 
of 95% of the users currently using the TESLAlogger.
I personally didn't wanted to have such a noisemaking device inside of my house ... thats why the 
Pi is such a smart thing to use ... low energy consumption and pretty easy forgettable until you need data from it.
To give you an update on the project  ...

_Currently the TL features_ 
- multi-cars in multi-accounts (tested against 20+)
- comunity comparision as the basis for a reliable fleet overview
- community donation of anonymized data to talk as a community member to TESLA on equivalent level of data
- docker support for those interested in having that architecture running
- tested TeslaFi & TM-Import functionalities
- new feature tests against a ev-car-equipped community
- onboard Data-Logging and aggregation  with ScanMyTesla (our partner software project with Amund)
- a strong community which extends the TL project with convenience features
- a comparison feature to allow a data-based decision regarding hardware improvements towards 
EV-efficiency inside of the cars (the other direction the company behind the TL is focussing on).
- support for several tesla owners in situations where they needed help to get some vital element of their 
EV as a part of the 8y waranty replaced from our beloved car manufacturer ... 
 
we keep you updated

**Comment by ngardiner** [comment]
None of the above is necessary at all? There's instructions on how to do a manual install in the docs. I use neither a NAS nor docker for my installation and it works fine. As I see it, docker is simply a convenience option for those who don't want to install postgres, teslamate and grafana manually, which is fine. That doesn't make it a requirement.

**Comment by ngardiner** [comment]
And further to that, the relatonship between a NAS and Docker is again non existent past the point that vendors such as QNAP or Synology include docker for convenience, so users can run containers on their NAS. You can run docker on a raspberry pi just fine....

**Comment by JakobLichterfeld** [comment]
> How has this comparison changed over the past 1.5 years? I am just deciding which project I should implement. Thanks! :-)

Hi ChrisPrefect,
if you can read german, you can find here a statement: https://tff-forum.de/t/teslamate-erfahrungs-und-datenthread/84179/45

Summarize from my point of view:
TeslaMate is modern SW development, inspired by TeslaLogger. There have been SW Architecture patterns right from the beginning, TeslaLogger was some sort of script-collection with some sort of UI and erosion over time.
TeslaLogger is no modern SW development in my eyes. Yeah, over time they include unit test, the mindset from beginning was not test driven development nor any other modern SW dev paradigma. Over time TeslaLogger was published as docker container as well, but to put something dirty in a bag it does not make it clean... TeslaLogger changed into a non 100% open project with a company behind it trying to sell raspberry pis with build in TeslaLogger. Even more TeslaLogger collect data of the users, yeah it is a feature as well, in the beginning the collection was not obviously to normal users, which is a total no-go from my point of view (links to conversation and findings see TFF post).
TeslaLogger has the build in ScanMyTesla for storing the values which are populated over OBD. This is for sure a unique feature. On the other hand it can cause serious failures, never mess the OBD :-)

Comparing the community is easy to compare by numbers: TeslaLogger has 126 Stars right now, TeslaMate has 1.2k...

So I dediced to go with TeslaMate and in the last 2 years I do not regret it

**Comment by DrMichael** [comment]
> i openly discussed with adrian why it seemed completely insane from my user perspective to first purchase a
> NAS and than besides that to implement by-hand a docker on it for a tesla car. This is above the config capabilities
> of 95% of the users currently using the TESLAlogger.
> I personally didn't wanted to have such a noisemaking device inside of my house ... thats why the
> Pi is such a smart thing to use ... low energy consumption and pretty easy forgettable until you need data from it.

Ok, that is obviously wrong (or outdated). 

> _Currently the TL features_
...

Boils down the the two points I mentioned, right?
