### ISSUE TITLE
IOS Shortcut to wake teslamate

### ISSUE THREAD

**Issue by drklain** [adriankumpf/teslamate#122]
Do you have an example or instructions on how to create the shortcut to:
- listen for the bluetooth connection
- call the http file in your instructions

**Comment by virtualm2000** [comment]
For the moment Automation for Shortcuts is not available. It was removed in the latest beta of iOS 13. Probably will be available in the final version of iOS 13. 

But you can still setup a shortcut and manually activate it when you are about to drive. You need this only when TeslaMate is waiting for the car to sleep. Bellow is the screenshot of my shortcut. Put your TeslaMate ip/hostname in the box. As per advice, be very careful with exposing your host to the internet. 

![IMG_EB388D549C98-1](https://user-images.githubusercontent.com/24257689/63755956-72101780-c8af-11e9-8fb5-af882083a63b.jpeg)

**Comment by drklain** [comment]
Thanks, that at least got it working manually.  I was using the link provided in the instructions (different http call) and it wasn’t reacting…guess I’ll wait for the final IOS13 and hope it allows for the automated call as well!

**Comment by bahree** [comment]
OK, so I got two instances running - one on docker on raspberry pi, and another one on docker on synology. Because of the other issues with synology ([see here](https://github.com/adriankumpf/teslamate/issues/108)), I created a raspberry pi one. Now the iOS shortcut works just fine with the instance running on synology, but when I try the same thing with the pi instance the http request times out. 

On both, the cURL command via the shell works, and I can ssh and browse to them and this is on my LAN, so can't think of any issues on what. My knowledge of docker is limited, so don't know what is different between the two that could cause this - especially from iOS.

From the phone, I can't even browse to the raspberry pi instance, but I can from other machines - I know this is scope creep but any pointers would be appreciated! Thanks.

**Comment by bahree** [comment]
I got this working, and I don't know why but I have had to plug in the Ethernet port, and continue to use the wifi. So this is working with that config. I also created two iOS shortcuts - which have a menu asking to resume or suspend, and using POST and another over ssh - happy to share if anyone is interested.

**Comment by drklain** [comment]
Would love to have the info on how you built the IOS shortcuts!

**Comment by bahree** [comment]
I got two versions - one inspired by @virtualm2000 's post here that uses HTTP PUT (essentially same thing at the curl command does) and another that SSH's in and then runs the command.

I published both of them here and you can get them from here @drklain.

TeslaMate Logging Toggle - https://routinehub.co/shortcut/3443
TeslaMate Logging Toggle (over SSH) - https://routinehub.co/shortcut/3444

I like RoutineHub, as it allows versioning, etc.

Feel free to extend as you feel fit. Let me know if you get into any issues. I only tried this from my and my wife's iPhone (two different models). Not had a chance to try it from an iPad just yet.

**Comment by Helmi** [comment]
just as a sidenote: iOS Shortcut Automations are back in iOS 13.1 which will be released in about 2 weeks, so should be possible to do the fully automatic way in iOS then without any 3rd party app (don't have a car yet to confirm).

**Comment by virtualm2000** [comment]
Unfortunately it's not fully automatic. Because of the security concerns you have to be authenticated with the phone (code is entered, fingerprint/faceid recognised) to run any automation. As it is now, a prompt appears to run your automation when the phone connects to the car. Maybe Apple will allow trusted automation to run without authentication but I think it will not happen.

**Comment by drklain** [comment]
Well that's at least somewhat better.  I look forward to the IOS 13.1 release...

**Comment by krezac** [comment]
@adriankumpf the "competition" project (https://github.com/lephisto/tesla-apiscraper) claims "Monitoring will continue within 60 Seconds on car usage.". Maybe the source code could be worth looking at.

**Comment by adriankumpf** [comment]
TM continues to poll the car when it is asleep and notices when the car wakes up. [This FAQ entry](https://github.com/adriankumpf/teslamate#sometimes-the-first-few-minutes-of-a-drive-are-not-recorded-even-though-the-car-was-online-why) explains why it may be advantageous to send the resume command manually anyway.

**Comment by krezac** [comment]
just FYI, no Shortcuts in iOS 13.0. It supposed to be in 13.1 (released planned for 24th).

**Comment by Helmi** [comment]
@krezac that info is already in this thread ;)

FYI: I finally got a phone that's able to read NFC tags (XS does it, and 11 Pro now does it too). NFC tags can be used for automation without confirmation. The phone doesn't even need to be unlocked. 

So this maybe an alternative - you can easily get some NFC tags from amazon and stick them somewhere in the car. You only need to tap them with the phone to get the automation going and wakeup TM.

**Comment by jmadra** [comment]
@Helmi there is one additional requirement if you are wanting to use iOS automation to run a shortcut to resume logging when triggered by reading the NFC tag - the URL for the PUT must use https otherwise the automation with throw an error (even though a resume shortcut using http will work fine on its own).
