### ISSUE TITLE
Failure in calculation?

### ISSUE THREAD

**Issue by ghostreader86** [adriankumpf/teslamate#131]
I just want to understand what the author of TeslaLogger said about the calucation of efficienty (I guess) and a potential fault in TeslaMate, see  [german forum post](https://tff-forum.de/viewtopic.php?f=58&t=24537&sid=1433794e4b570acc54726fc507c86ce2&start=1320#p798047).
Can you ad your 2cents? 
Thanks.

**Comment by adriankumpf** [comment]
He's probably referring to the efficiency factors / "Wh_km" that are part of the vehicle detection: 

https://github.com/adriankumpf/teslamate/blob/d0cec8435d37db00018bdd4088302c6c87e257e5/lib/teslamate/vehicles/identification.ex#L31-L59

I  copied those factors since that is most reliable source I found. I could only verify the given factor for the Model 3 (`0.153`). Some factors might be inaccurate and for some vehicles there simply is no factor. So he's right, that might lead to inaccurate or empty consumption values. Also, the way the calculation is done (by both TeslaLogger & TeslaMate) is by no means 100% accurate. It's more or less an estimation. Although it should be fairly accurate in most cases (given the efficiency factor is correct).

I also think his approach of collecting user data to improve those factors is perfectly valid. It might have been better to make that decision transparent to the users, but that's just my 2 cents. 

With TeslaMate v1.7.0 there now is a dashboard panel that shows the derived efficiency factors for the users vehicle. If someone notices a discrepancy between the default and the derived factor he/she can create an issue, so that the default factors can be updated. I prefer that crowdsourcing approach and hope that this will help to complete the missing factors.

**Comment by adriankumpf** [comment]
Oh, I almost forgot: thank you for bringing up TeslaMate in the TFF forum! All my posts mentioning TeslaMate got blocked (had a fresh account).

**Comment by ghostreader86** [comment]
Thanks. Yeah I spot your crowdsourcing approach in the code already, just keep my eyes on commits the last week 😉

**Comment by DrMichael** [comment]
Wouldn't an own thread make sense in TFF?
Or is this here the place to discuss and ask questions?

**Comment by adriankumpf** [comment]
I have lost my interest in this forum ever since they blocked all my posts that mentioned TeslaMate, to be honest. I don't like that gatekeeping approach. 

GitHub is definitely the better place. It also makes it easier to keep track of issues and feature requests since everything is neatly separated instead of one long thread.

I like the idea of spreading the word on TFF though ... :D

**Comment by DrMichael** [comment]
> GitHub is definitely the better place. It also makes it easier to keep track of issues and feature requests since everything is neatly separated instead of one long thread.

Indeed, I agree. I only looked into Teslamate today, but I've got the impression of a very lively community here.

> I like the idea of spreading the word on TFF though ... :D

:-) Let's go...
