### ISSUE TITLE
Charge records not being displayed

### ISSUE THREAD

**Issue by thunder2k** [adriankumpf/teslamate#1590]
**Describe the bug**

No records are displayed in the dashboard "Charges" for the last 24 hours. You can see the car did charge from the "States" dashboard.

![image](https://user-images.githubusercontent.com/43518960/117045413-653ffa00-ad07-11eb-8926-7e27976be92c.png)

**Expected behavior**

See charges records

**How to reproduce it (as minimally and precisely as possible)**:

1. Go to Charges Dashboard
2. See Records in the last 2 days

**Relevant entries from the logs**

```
`docker-compose logs teslamate` erroring out:
-bash: Attaching: command not found
```

**Screenshots**

**Data**
Attached charge data from the last 2 days
[charge_data.zip](https://github.com/adriankumpf/teslamate/files/6422952/charge_data.zip)

**Environment**

- TeslaMate version: 1.22.0
- Type of installation: Docker
- OS TeslaMate is installed on: Raspbian 10
- User OS & Browser: Windows 10 - Chrome
- Others:

**Comment by adriankumpf** [comment]
The recorded charge records are not displayed because effectively no range was added. At least this is what seems to have been reported by the API. 

Extract from the `charging_processes.csv` you added:

|start_date             |end_date               |charge_energy_added|start_ideal_range_km|end_ideal_range_km|start_battery_level|end_battery_level|duration_min|start_rated_range_km|end_rated_range_km|charge_energy_used|
|-----------------------|-----------------------|-------------------|--------------------|------------------|-------------------|-----------------|------------|--------------------|------------------|------------------|
|2021-05-03 01:58:00.792|2021-05-03 02:00:10.949|0.00               |296.39              |297.94            |80                 |80               |2           |296.39              |297.94            |                  |
|2021-05-03 03:04:22.007|2021-05-03 03:06:31.852|0.00               |296.39              |297.17            |80                 |80               |2           |296.39              |297.17            |                  |
|2021-05-03 07:28:54.844|2021-05-03 07:31:11.301|0.00               |294.85              |297.17            |80                 |80               |2           |294.85              |297.17            |                  |
|2021-05-03 05:16:58.905|2021-05-03 05:18:47.761|0.00               |296.39              |297.17            |80                 |80               |2           |296.39              |297.17            |                  |
|2021-05-03 09:41:26.852|2021-05-03 09:43:16.209|0.00               |294.85              |297.17            |80                 |80               |2           |294.85              |297.17            |                  |
|2021-05-03 17:24:00.4  |2021-05-03 17:25:50.483|0.00               |295.62              |297.17            |80                 |80               |2           |295.62              |297.17            |                  |
|2021-05-03 10:47:14.893|2021-05-03 10:49:27.537|0.00               |294.85              |297.17            |80                 |80               |2           |294.85              |297.17            |                  |
|2021-05-03 15:11:37.71 |2021-05-03 15:13:49.192|0.00               |295.62              |297.17            |80                 |80               |2           |295.62              |297.17            |                  |
|2021-05-03 11:53:09.382|2021-05-03 11:55:28.749|0.00               |294.85              |297.17            |80                 |80               |2           |294.85              |297.17            |                  |
|2021-05-04 16:18:21.865|2021-05-04 16:27:15.879|0.00               |289.44              |297.13            |78                 |80               |9           |289.44              |297.13            |1.03              |
|2021-05-03 12:59:36.642|2021-05-03 13:02:23.306|0.00               |295.62              |297.17            |80                 |80               |3           |295.62              |297.17            |                  |
|2021-05-03 18:29:46.381|2021-05-03 18:31:56.943|0.00               |295.62              |297.17            |80                 |80               |2           |295.62              |297.17            |                  |
|2021-05-03 23:53:47.374|2021-05-04 00:02:24.372|0.00               |289.44              |295.59            |78                 |80               |9           |289.44              |295.59            |0.93              |
|2021-05-03 14:05:22.739|2021-05-03 14:07:39.231|0.00               |296.39              |297.17            |80                 |80               |2           |296.39              |297.17            |                  |
|2021-05-03 16:17:41.434|2021-05-03 16:19:54.448|0.00               |295.62              |297.17            |80                 |80               |2           |295.62              |297.17            |                  |
|2021-05-04 10:51:01.717|2021-05-04 10:59:28.996|0.00               |289.44              |297.13            |78                 |80               |8           |289.44              |297.13            |0.98              |
|2021-05-04 05:21:57.608|2021-05-04 05:31:19.694|0.00               |289.44              |297.13            |78                 |80               |9           |289.44              |297.13            |1.09              |
