### ISSUE TITLE
Just want to say thanks for this AWESOME bit of software!

### ISSUE THREAD

**Issue by sumnerboy12** [adriankumpf/teslamate#1662]
No bug to report, just wanted to pass on my gratitude for such a well designed and implemented bit of software.

I use this almost daily to track my Tesla's performance and love seeing the new dashboards and views being added all the time.

You must spend a lot of time working on this, so just wanted to say **THANKS**!!

**Comment by adriankumpf** [comment]
Thank you very much!

**Comment by mikeh2010** [comment]
+1 from me. It is an amazing bit if coding.

Thanks 👍🏻

**Comment by Powerbook001** [comment]
Can I also get the chance to say thank you?

I will get my first Tesla after tomorrow, and I must confess that searching around the web, while waiting for the delivery day, trying to know as much as cood of this astonishing machine, I discovered I do not remember how, you're software and since I love telemetry in any device, due to my field of work (aeronautics). I fell in love with it. And I must say that it's a really nice peace of work, what you did. Danke Adrian.

Nico - Italy

**Comment by jannyg** [comment]
Signed! If you want to, please follow my example and use the donation button in the footer of the Teslamate dashboard to show our appreciation and to help @adriankumpf with future development 🚀

**Comment by wesleycheung0** [comment]
I would like to add another thank you note to the owner and all the contributors for the work. 

I wish I have found teslamate sooner, and only start logging after 4000miles.

**Comment by SigLinJo** [comment]
I also want to add my praise of Adrian and this really high quality project! I've used it for almost two years and it's so nice to be able to track all the data in such a well made software. I've had very few problems and none that were not of my own making, and the agile and continues development is really good! I even host teslamate for my brother and a friend so that they can keep track of their cars in a safe and feature rich way! Thank you!

**Comment by sumnerboy12** [comment]
> Signed! If you want to, please follow my example and use the donation button in the footer of the Teslamate dashboard to show our appreciation and to help @adriankumpf with future development 🚀

Done!

**Comment by noocyte** [comment]
Just adding my gratitude as well - love Teslamate. Been donating a small amount every month since December 2020 (when I picked up my very first Tesla).

**Comment by tfsjohan** [comment]
Agree! This is super useful! 
Often show it to my non-tesla-friends and they wish they could have something similar for their cars.

**Comment by seabie** [comment]
> Signed! If you want to, please follow my example and use the donation button in the footer of the Teslamate dashboard to show our appreciation and to help @adriankumpf with future development 🚀

DONE!

**Comment by denisjoshua** [comment]
Thanks a lot :-)

**Comment by sumnerboy12** [comment]
Thanks again @adriankumpf - closing this issue now!
