### ISSUE TITLE
Charging Details - 4 phases

### ISSUE THREAD

**Issue by krezac** [adriankumpf/teslamate#178]
Charging details dashboard shows 4 phases - car is on 3-phase wallbox. Recent 1.9.0 version (EDIT: I don't know if it was there before).

![image](https://user-images.githubusercontent.com/16595657/65536807-65a9c980-df04-11e9-8beb-488ccf79039e.png)

**Comment by adriankumpf** [comment]
Do you have any previous charges to compare to? Which firmware version is installed?

**Comment by krezac** [comment]
All values are 4 (actually, six are empty):
teslamate=# select distinct charger_phases, count(*) from charges group by charger_phases;
 charger_phases | count
----------------+-------
              4 |  1492
                |     6

Car is on 2019.28.3.1 (no info about newer version yet)

**Comment by adriankumpf** [comment]
Interesting. The API frequently reports 2 phase charging instead of 3 (at least with the Model 3). That led me to think it the number is generally off by one but it seems to be an internal firmware bug. That's why TeslaFi recently added a phase correction to tagged locations. I thinks it's best to use the reported value from the API for now.

**Comment by krezac** [comment]
Feel free to close in that case. Thx for checking (I wondered if it could be issue decoding some packed format).

**Comment by adriankumpf** [comment]
Thanks for reporting! Fixed by 796d81c.
