### ISSUE TITLE
Divide by zero in Grafana dashboards

### ISSUE THREAD

**Issue by gryghst72** [adriankumpf/teslamate#2063]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In "Projected Range - Battery Level" dashboard (and others), I am getting a divide by zero error.  For any panel that includes battery level or useable battery level divisors when those values can be 0 (as has happened to my battery), the "Divide by Zero" error will occur. 

### Expected Behavior

Would like to see the same divide by zero protection for the Battery Level and Outdoor Temp as was implemented in Mileage:

From:       "rawSql": "SELECT\n\t$__timeGroup(date,[[interval]]) AS time,\n\tconvert_km(sum([[preferred_range]]_battery_range_km) / sum(coalesce(usable_battery_level,battery_level)) * 100, '$length_unit') AS \"Projected Range (using usable_battery_level) ...

To:       "rawSql": "SELECT\n\t$__timeGroup(date,[[interval]]) AS time,\n\tconvert_km(sum([[preferred_range]]_battery_range_km) / nullif(sum(coalesce(usable_battery_level,battery_level)),0) * 100, '$length_unit') AS \"Projected Range (using usable_battery_level) ...

I'm not sure what the nullif() function does, but it prevents the error in my local testing.

### Steps To Reproduce

Have a selected record where "usable_battery_level" or "battery_level" is 0 and the Grafana panel uses one of these as a divisor. 

### Relevant log output

```shell
None
```

### Screenshots

![image](https://user-images.githubusercontent.com/54452464/137507290-320afa71-aace-4c8f-be41-0bc6c08639bd.png)

### Type of installation

Docker

### Version

v1.24.2

**Comment by gryghst72** [comment]
At the lowest battery level point, the projected range shoots way up:

@ 1%
![image](https://user-images.githubusercontent.com/54452464/137550674-430d6f44-31d6-4ef9-b27b-896b90b45f01.png)

@ 0% and Projected Range using Usable_Battery_Level is blank:
![image](https://user-images.githubusercontent.com/54452464/137550555-d63832e9-5cab-438e-b9a0-0ccf7d8a53f0.png)

**Comment by sparkstack1** [comment]
Seeing the same divide by zero errors in the following dashboards.

Updates, Projected Range.

<img width="332" alt="Screen Shot 2022-01-12 at 9 54 36 PM" src="https://user-images.githubusercontent.com/97652274/149264379-f4205443-e747-46ca-b166-bd7b78787faa.png">

<img width="394" alt="Screen Shot 2022-01-12 at 10 04 31 PM" src="https://user-images.githubusercontent.com/97652274/149264394-c80b4eba-04f2-4a93-8eac-8e0d3cb48dea.png">

Seems to be due to a charge level of 0 percent one time in the last 90 days, which also erroneously spikes the projected range.  Hopefully a fix comes soon.

<img width="541" alt="Screen Shot 2022-01-12 at 10 12 49 PM" src="https://user-images.githubusercontent.com/97652274/149264728-8c97717e-4199-42e2-909a-143fe26ecf9d.png">

<img width="831" alt="Screen Shot 2022-01-12 at 10 04 54 PM" src="https://user-images.githubusercontent.com/97652274/149264413-551c617c-e384-43ee-b21e-d78fef358de8.png">

**Comment by NikodFr** [comment]
Hi 👋 
Same problem here. 
Some panels (Updates, Projected Range - Battery Level and Projected Range - Outdoor Temp) show the error "pq: division by zero".

![Capture d’écran 2022-01-24 à 23 52 30](https://user-images.githubusercontent.com/98359963/150878295-49db6191-5086-4216-9cc0-a14931eb4278.png)

And I also once had a usable battery level at 0%.

![Capture d’écran 2022-01-24 à 23 45 00](https://user-images.githubusercontent.com/98359963/150878034-5c793f37-b67e-4f27-a2d5-ed1745c9e43f.png)

@adriankumpf  Is it possible to delete from the database all the data that was collected that day to avoid this error?

**Comment by sparkstack1** [comment]
The issue is tied to the battery being at zero. I really hope a fix is on the way without having to resort to deleting data.

**Comment by NikodFr** [comment]
I'm also hoping for a fix but in the meantime if deleting some data could solve the problem, I'll take it...

**Comment by johndescs** [comment]
Same here, my battery had to be changed, and range and level went through 0 so I got a divide by 0 in the panels you mention. 
Was willing to try to patch this but going through all the docker stuff or installing elixir & co on my machine looked boring for such a small issue that would probably take like 5 minutes for someone already in the project :)

**Comment by Dulanic** [comment]
Can anyone give me a sample drive to test this with? The SQL code already nulls the 0 in the denominator? Not sure why this error would be happening. A 0 would be fine in the numerator.
