### ISSUE TITLE
No consumption data on new installation

### ISSUE THREAD

**Issue by walkercam** [adriankumpf/teslamate#2272]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Teslamate has been up and running for several days now with multiple drive and charge cycles. All data appears to be showing correctly however I have a complete lack of energy consumption data. I have gone through some of the past issues and it appears there may be others with a similar issue but with no resolution. I've gone through all of the settings and documentation without finding a possible solution. 

Car is a new Chinese assembled M3 SR+.

![image](https://user-images.githubusercontent.com/133103/147896963-25242dc3-30aa-4439-819a-5405ee7da7ce.png)

### Relevant log output

```shell
No obvious issues in the logs (although I'm no expert)
```

### Type of installation

Docker

### Version

1.25.0

**Comment by BabyYeggie** [comment]
Efficiency is not calculated for drives of less than 1km.

**Comment by DrMichael** [comment]
Could well be, that efficiency is empty. What gives `select id, efficiency from cars;`?

That should be filled after a while...

**Comment by niklasfink** [comment]
This is the same problem I'm having and what we already started discussing in #2229. However, since #2229 is probably a slightly different problem (because the issue opener is seeing kWh values, but no efficiencies), I'll continue here.

My cars also do not have an efficiency value, even though they have been charged multiple times for more than 30mins and have lots of drives.

I have found the following in the code base in the `recalculate_efficiency` func:
https://github.com/adriankumpf/teslamate/blob/41f1280e75e8f48db702f18755e1ce0ab1f044bd/lib/teslamate/log.ex#L605

Since there is no documentation on the efficiency feature, I can only guess from that little snippet, that the efficiency is calculated after a charging cycle with very specific properties, such as duration>10, end_battery_level<95 ...

In my case, I mostly charge to 100%, which probably a lot of SR+ LFP battery owners will do.

@adriankumpf what is the reasoning behind the efficiency calculation only being done for charging cycles with end_battery_level<95?

**Comment by niklasfink** [comment]
I finally received an efficiency value for one of the monitored cars after I stopped the charge at 90%. 

Seem like there are quite a few conditions until an efficiency value is calculated. This is currently not explained in the FAQ, therefore a lot of questions are coming up.

![image](https://user-images.githubusercontent.com/1809301/148176911-98055daf-dd49-4e8d-83ee-dc87c1ade828.png)

**Comment by walkercam** [comment]
Thanks @niklasfink . I understand what the issue is here now. I have been misinterpreting the meaning of the 'efficiency' variable that has been mentioned in this issue and in others. After having a dig through the SQL queries in Graphana and the comments you made above the penny has finally dropped. I had assumed that the efficiency value was simply the values being populated for each drive (eg in your screengrab above the 242, 52, 80, 85% etc). It may be worth changing this terminology so as to not confuse new users such as myself. Indeed car.efficiency has still not been populated.

As my car is also an LFP car I always charge to 100% when charging at home. I'm sure my issue will be the same as @niklasfink . I will reduce the max charge to 90% and see if this fixes my issue. 

In the long term there will need to be a fix for this as LFP battery owners will want to charge to 100% each charge cycle and is Teslamate is not using data from charges over 95% the long term accuracy of the efficiency may not be very high (even if the user does a short term reduction to 90% max charge to populate the figure).

**Comment by walkercam** [comment]
Excellent! I now have consumption data showing. I'll leave my charge limit set to 90% for a few days to increase the accuracy of the efficiency number. Is there any other advice for dealing with charging to 100%?

![image](https://user-images.githubusercontent.com/133103/148698837-268adeba-796d-4e40-8ab5-d883b1479861.png)
