### ISSUE TITLE
Map location in charge details

### ISSUE THREAD

**Issue by cwanja** [adriankumpf/teslamate#240]
**Describe the bug**
Following the most recent update (I assume), going into the charge details does not show the location of the charge. The map just loads to an overview of the entire map. Zooming into the location does not have a dot like it used to either.

**However**, the location still shows in the table of charges 

**To Reproduce**
1. Load up Grafana
2. Load up the Charge dashboard
3. Click on any Charge
4. View map on selected Charge via the Charge Details dashboard

**Expected behavior**
A dot should be located on the map via the location obtained via the API during the charging session.

**Screenshots**
![Screen Shot 2019-11-05 at 6 26 24 PM](https://user-images.githubusercontent.com/54645561/68257707-c9daa580-fff9-11e9-90d7-b12d4df56428.png)

**Operating environment (please complete the following information):**
 - OS: [Raspberry Pi Rasbian]
 - TeslaMate [v1.12]

**Comment by tucopup** [comment]
Following your steps 1-4 above, I see an error in the top left of both the charge details windows and the map window: pq: syntax error at or near ",".   No data in either window.

I also note the car drop-down selector shows "2,1,3" instead of the three car names.  At this point, I can select in the drop down the vehicle whose charge I picked and then the data displays.  No dot in the map.  Until I zoom out the time range.  Dot appears when cursor is over left graph.

If I select any other vehicle there is no data (as expected) until I zoom out.  Dot is present, everything normal.


Synology; Teslamate 1.12.1

**Comment by spacecosmos** [comment]
I also tried to reproduce the bug. For me it always zooms _to_ the correct location, but the dot itself is _absent_.

That said, I'm not entirely sure _when_ this started to happen though. Because I haven't been looking for the dot itself as I've always seen the map _zoom in_  - which for me is the most important part.

**Comment by spacecosmos** [comment]
I also tried to reproduce the bug. For me it always zooms _to_ the correct location, but the dot itself is _absent_.

<img width="1561" alt="Screenshot 2019-11-06 at 09 20 08" src="https://user-images.githubusercontent.com/55928670/68281315-b3732f00-0077-11ea-8d41-e5fae3d47fff.png">

That said, I'm not entirely sure _when_ this started to happen though. Because I haven't been looking for the dot itself as I've always seen the map _zoom in_  - which for me is the most important part.

**Comment by vkarthikbalaji** [comment]
Looks like the event is not updating sometimes. For eg. some specific charge displays details with proper scaling and translating the lat-long. However, some not. Double clicking on the charge graph on the left zooms in on the right location. @spacecosmos, If you move the cursor over the charge graph(left side), then the point will appear.

**Comment by spacecosmos** [comment]
> @spacecosmos, If you move the cursor over the charge graph(left side), then the point will appear.
> 

@vkarthikbalaji - Yes, I found that out now, I kind of just forgot that I used to do it before. Anyways, I'm also fairly sure that the dot was there constantly before. But I could be mistaken of course. :)

**Comment by cwanja** [comment]
@spacecosmos like you, I cannot recall specifically if it was supposed to always be present or only showed when you moused over the charge graph. However, since I feel like your car is _never_ moving during the charge session (unless there is something I do not know), it seems like it would make sense for the dot to be persistent. Maybe this is not a bug, but a feature enhancement if it previously took you mousing over the charge graph to have the dot show.

**Comment by adriankumpf** [comment]
I'm pretty sure that the blue dot has never been displayed unless one is hovering over the graph. My hands are tied here: the maps plugin (https://github.com/pR0Ps/grafana-trackmap-panel) does not offer more customization options.

As for your main issue, @cwanja: Is the location not present for all or only few charges? Is it displayed when you zoom out?

**Comment by spacecosmos** [comment]
So, I took another look and I actually _do have_ a small red dot there. This is consistent with what I thought I had for a long time. I have no clue why it comes and goes though...

<img width="1557" alt="Screenshot 2019-11-06 at 18 00 08" src="https://user-images.githubusercontent.com/55928670/68320095-a5490100-00bf-11ea-922d-df9174c6844c.png">

PS! I'm _not_ hovering or clicking over the graph itself.

Installation type:
v1.12.2
Docker running on Ubuntu (DigitalOcean)

**Comment by adriankumpf** [comment]
This red dot came up with v1.12.2 in response to this thread :)

**Comment by cwanja** [comment]
@adriankumpf if I recall, it was not there for any of the five or six charges that I sampled. And these were sampled over the last month or two. I saw nothing when I zoomed in or out of the location on the map. 

I will check again when I get home **prior** to updating to V1.12.2.

**Comment by cwanja** [comment]
A few things:
- historically, the dot **would not** show until you moused over the graph. However the map was zoomed into the location on the map where the dot basically would be centered. This _might_ be because I have a geofence setup, but cannot confirm as I have only ever charged at home 🤷🏽‍♂️ (sorry)
- somewhere between 10/17 and 10/20 (two dates I charged), the map stopped zooming in to the location where the charge took place. 

Updating to V1.12.2 now.

**Comment by cwanja** [comment]
Seems like the same issues persists through V1.12.2. Although my little Pi is struggling.
