### ISSUE TITLE
Drive data missing

### ISSUE THREAD

**Issue by rakle** [adriankumpf/teslamate#244]
I'm using TeslaMate for a couple of weeks now, and everything works very well. Thanks for this great project!

But after checking my drives yesterday I saw one about 30 minute drive missing completely - no entry in Grafana, no drive or position data in the database. The states data show that the car was sleeping the whole time. The next drive after a couple of hours was logged without any problems.

Has anybody faced a similar problem before? Is this more an issue of the data provided by the Tesla network/API than of TelsaMate?

Thanks & Best regards

**Comment by adriankumpf** [comment]
Did that happen again afterwards? Was the car already sleeping or was it just falling asleep? If the latter was the case, the problem could be addressed by [providing wake-up hints to TeslaMate](https://github.com/adriankumpf/teslamate/blob/master/docs/configuration/sleep.md#providing-wake-up-hints-to-teslamate). Otherwise, we'd have to take a closer look at the logs (`$ docker-compose logs teslamate`) to identify the problem.

**Comment by rakle** [comment]
It didn't happen the same way, that a whole drive was missing completely. But it happens, that while driving the log suddenly stopped with error messages (see below). Sounds to me more like an issue of Tesla or the vehicle firmware than of TeslaMate?

![image](https://user-images.githubusercontent.com/57400629/68993104-7592b980-0874-11ea-9595-9437119ce04e.png)

**Comment by adriankumpf** [comment]
Looks like it, yeah. From my experience the error messages above are usually a sign of a slow Internet connection or poor reception. And these 408 errors are often result of a server problem.

**Comment by rakle** [comment]
Thanks for your reply and the background infos!

**Comment by timguy99** [comment]
I'm getting a lot of these 408 errors and upstream timeouts as well. Seems like just recently as I have never had a drive NOT logged yet. Now I've had 3-4 already within 24 hrs.
