### ISSUE TITLE
Teslamate interfering with Sentry Mode

### ISSUE THREAD

**Issue by tchlyah** [adriankumpf/teslamate#247]
**Describe the bug**
I have a really weird bug with Teslamate and Sentry mode: After activating Teslamate on my server, nearly most of the videos recorded by Sentry mode are empty (~500kb). I have bought a Samsung T5 SSD to avoid these issues as I saw that there are quite common.

I've tried a lot of things, reformatting the SSD, paying attention to disable both Sentry and Dashcam before ejecting it, removing JEDA USB Hub... The only thing that worked, is disabling Teslamate.

I noticed that the car never sleeps, but I think it is an expected behavior when enabling 24/24 Sentry mode

**To Reproduce**
Just connecting Teslamate with my account.

**Expected behavior**
Teslamate shouldn't interfer with Sentry mode

**Operating environment (please complete the following information):**
 - OS:  Docker version 19.03.4 on Debian GNU/Linux 9.11 (stretch)
 - Version: latest

**Comment by adriankumpf** [comment]
I don't mean to upset you, but I really doubt it.

All TeslaMate or any other logger do is issue requests to the Tesla API. The same requests are made by the official Tesla app. So if you’ve used the app before installing TM and the sentry mode worked at that time, that would be a strong sign that the problem must be somewhere else.

If this were really the case then it would be a firmware bug of the vehicle and not a problem with the software accessing the vehicle via the API.

**Comment by tchlyah** [comment]
I totally agree with you, it doesn't seem logic. But I wouldn't post this issue if I weren't sure.

I disabled Teslamate for a couple of days, all videos were perfect, no loss. Yesterday I enabled it again, no same bug, so I'm pretty sure it is because of it.

I have no problem with Tesla and [Stats](https://apps.apple.com/fr/app/stats-for-tesla-model-s-x-3/id1191100729) apps.

Maybe it is the Time to Try Sleeping configuration, which by the way, even after reading the documentation, I couldn't understand exactly what it does. I'm guessing that it tells the car to sleep, which interferes with Sentry mode, as the car should always be up in this mode.

**Comment by adriankumpf** [comment]
Let me know if you find out more about it or if something changes with the next vehicle software update.

**Comment by ngardiner** [comment]
> Maybe it is the Time to Try Sleeping configuration, which by the way, even after reading the documentation, I couldn't understand exactly what it does. I'm guessing that it tells the car to sleep, which interferes with Sentry mode, as the car should always be up in this mode.

All it does is hold off on actively polling the car to let it go to sleep.

If what you were saying were the case, I'd have the exact same issue as you, as I also have a Samsung T5 SSD and run TeslaMate. I have Sentry enabled everywhere but at home. I've never had the issue you're reporting.

What you are saying seems very deterministic - the problem is every other person using it would have to not be using sentry for it to be TeslaMate's polling mechanism, and I don't think you'll find that is the case. If I were you, I'd start with a service call to Tesla, something I would do regardless if my Sentry Mode did not work. It's possible (and I'd say highly likely off the description you've given of the behaviour) that it is an issue with your vehicle.

This hypothesis seems to be based on the idea that TeslaMate is querying or utilising some API endpoint or mechanism that every other system you've used does not, and there's little to no likelihood that is the case - especially as something like the Tesla app pulls all of the polling data that TeslaMate does, but also allows calling remote functions (such as lock, unlock, etc) that TeslaMate does not - effectively it is that TeslaMate is a simple pull mechanism with backoff algorithm for allowing sleep, I don't see how it would be implementing anything those other systems are not.

**Comment by ngardiner** [comment]
Here's the documentation on how the sleep mechanism works:

https://github.com/adriankumpf/teslamate/blob/master/docs/configuration/sleep.md

Let me know if there's any areas that are unclear that need further clarification and I am happy to work on them, but you'll note that the mechanism is based on a back-off/polling suppression rather than active commands being sent to the vehicle. The worst that should be happening is that your vehicle doesn't sleep, which as you correctly pointed out, is the case if Sentry Mode is active anyway.

**Comment by tchlyah** [comment]
After updating the car in latest version (2019.36.2.1), everything was working as expected but just 1 day. After that, I lost almost all my videos. As soon as I stop Teslamate, all videos are working great. So I'm still having the issue.

It's sad because I love and I need Teslamate but I can't use it since Sentry videos are very important!

Did you try to reproduce the bug before closing the issue ? Maybe the condition is running Sentry mode  24/24 and not disabling it at home and/or office.

Can you please try that I see if you can reproduce the problem?

Also, if I'm the only one having the issue, how can I prove to Tesla that the bug is coming from my car?

**Comment by cavit99** [comment]
It's very very odd and I realise causality is difficult to establish but since installing teslamate I'm also strangely having issues with Sentry too, these years later. Basically no videos are recorded in sentry mode. I tried formatting drive, replugging etc to no avail. Only seems to affect Sentry, not dashcam, which are in fact recorded.  I'll report back once I disable teslamate and see if it comes back.


> After updating the car in latest version (2019.36.2.1), everything was working as expected but just 1 day. After that, I lost almost all my videos. As soon as I stop Teslamate, all videos are working great. So I'm still having the issue.
> 
> It's sad because I love and I need Teslamate but I can't use it since Sentry videos are very important!
> 
> Did you try to reproduce the bug before closing the issue ? Maybe the condition is running Sentry mode 24/24 and not disabling it at home and/or office.
> 
> Can you please try that I see if you can reproduce the problem?
> 
> Also, if I'm the only one having the issue, how can I prove to Tesla that the bug is coming from my car?

**Comment by souni** [comment]
I'm having very same problem. My car was upgraded from MCU1 -> MCU2 few weeks ago and when I put the Sentry mode on it didn't record anything even when the screen went on and said recording. Manual recording worked. Service said that sentry mode is acting weird and asked if I have any 3rd party apps connecting to the car and asked to turn them off. Then I shut down TeslaSpy and TeslaMate and everything started working. I thought it was because I had two apps simultaneously fetching data from the car.

Then I tried to turn on only one of them. First TeslaSpy. I let it fetch data for one week and the Sentry worked as expected and events were recorded. Then I turned TeslaSpy off and turned TeslaMate (in streaming mode) on. After two days it stopped recording Sentry events. 

Sometimes it wakes up to "record" as the screen turns on and sometimes it won't even turn the screen on when going near the car. In both cases it is not saving any footage. If I go in the car when it says it recording, it shows to be saving the footage (down arrow next to Sentry icon) but If I check the viewer after that there isn't any recording for the event. I have checked the memory card also with computer and recovery software but there isn't any mark of the recording.

So some how TeslaMate get's my Sentry mode in unstable state.

**Comment by cavit99** [comment]
> I'm having very same problem. My car was upgraded from MCU1 -> MCU2 few weeks ago and when I put the Sentry mode on it didn't record anything even when the screen went on and said recording. Manual recording worked. Service said that sentry mode is acting weird and asked if I have any 3rd party apps connecting to the car and asked to turn them off. Then I shut down TeslaSpy and TeslaMate and everything started working. I thought it was because I had two apps simultaneously fetching data from the car.
> 
> Then I tried to turn on only one of them. First TeslaSpy. I let it fetch data for one week and the Sentry worked as expected and events were recorded. Then I turned TeslaSpy off and turned TeslaMate (in streaming mode) on. After two days it stopped recording Sentry events.
> 
> Sometimes it wakes up to "record" as the screen turns on and sometimes it won't even turn the screen on when going near the car. In both cases it is not saving any footage. If I go in the car when it says it recording, it shows to be saving the footage (down arrow next to Sentry icon) but If I check the viewer after that there isn't any recording for the event. I have checked the memory card also with computer and recovery software but there isn't any mark of the recording.
> 
> So somehow TeslaMate get's my Sentry mode in unstable state.

I was was having this issue until moved teslamate to local. Are you running in the cloud?

**Comment by souni** [comment]
Yes, it's running at Digital Ocean. Very strange. I'll guess that network speed and latencies changes with local (home?) installation. But hard to guess why would that affect the Sentry mode. @adriankumpf any thoughts?

Did you have any other setup changes from cloud to local installation?

**Comment by cavit99** [comment]
Yes exactly same config running on Pi at the office. Was running on AWS before, which I would have preferred but was very weirdly having this issue with Sentry. Mine lives on a public road so I can’t not have Sentry work. I think it’s a weird API issue on tesla side rather than teslamate

**Comment by souni** [comment]
Yep, I agree, but I don't know if Tesla API will be fixed any time soon. I just got the car from the service and it says that the mobile application layer is acting strange and it leads to situation where part of vehicle systems thinks that sentry mode is ON and some parts of systems thinks sentry mode is OFF. That makes it seem like sentry is ON but it's not recording video. It also states that customer is using 3rd party apps simultaneously and switching those off will make sentry video recording to work.
