### ISSUE TITLE
Home Assistant Conversions

### ISSUE THREAD

**Issue by kinteseay** [adriankumpf/teslamate#263]
I understand that this is not a teslamate issue, but I'm trying to display my info in home assistant.  I'm in the USA and prefer to view in miles.  I'm getting the info from MQTT, which is in km.  I attempted to convert the data, but I'm getting 0 value for miles.  Can someone help me edit my .yaml file.  This is an example of what I have:

  - platform: mqtt
    name: tesla_estimated_range
    state_topic: "teslamate/cars/1/est_battery_range_km"
    unit_of_measurement: 'mi'
    value_template: >
          {{ states('teslamate/cars/1/est_battery_range_km')|float/1.609|round(0) }}
    icon: mdi:map-marker-path

Thanks

**Comment by nicholsongreg** [comment]
Hi!

The problem is in your value_template part.  You can't reference the topic like a state.

However, you CAN reference it as value.

so: 

value_template: >
{{ value|float/1.609 }}


Also, in your example, you want to use parens to make sure that you are rounding the converted value, and not the 1.609.

**Comment by kinteseay** [comment]
> Hi!
> 
> The problem is in your value_template part. You can't reference the topic like a state.
> 
> However, you CAN reference it as value.
> 
> so:
> 
> value_template: >
> {{ value|float/1.609 }}
> 
> Also, in your example, you want to use parens to make sure that you are rounding the converted value, and not the 1.609.

Thank you,

That worked
