### ISSUE TITLE
Fill default data

### ISSUE THREAD

**Issue by BabyYeggie** [adriankumpf/teslamate#265]
Certain types of data have no initial data or requires up to 3 changes before it's recorded in the database. For example, the "updates" requires 3 updates despite the current FW being available in the Teslamate screen. I've had 2 updates but the database still shows "no data to show".

Perhaps populate certain fields based on the first available dataset such as: firmware version, current SoC, current range, odometer reading, etc.

**Comment by adriankumpf** [comment]
Sorry but I don’t quite follow you. Updates are recorded and displayed immediately. Was TeslaMate already running when you installed those 3 updates? Note that historic data cannot be pulled from the vehicle.

**Comment by spacecosmos** [comment]
I think he means that no firmware version shows up in the firmware box in i.e **Overview**.

<img width="586" alt="Screenshot 2019-11-26 at 15 08 31" src="https://user-images.githubusercontent.com/55928670/69640905-79d28a00-105f-11ea-9949-3e9f34202a82.png">

I just added my parents car as a second car and the firmware doesn't show up on their Model 3 either. (Mine is fine though.)

<img width="573" alt="Screenshot 2019-11-26 at 15 15 02" src="https://user-images.githubusercontent.com/55928670/69640978-a1295700-105f-11ea-8914-016e61ac7e5a.png">

Any idea what could be the issue?

**Comment by airmaxx** [comment]
For me Firmware showed up after Teslamate registered the first firmware upadate - initally it was also empty.

**Comment by spacecosmos** [comment]
> For me Firmware showed up after Teslamate registered the first firmware update - initally it was also empty.

It shows the correct firmware on the TeslaMate Dashboard site, so it's only on the Grafana site it doesn't show up. But like you said, maybe it's because it hasn't been updated and there isn't a value in the database yet. Unless this can be written in there somehow, without doing an update first.

<img width="460" alt="Screenshot 2019-11-26 at 15 37 40" src="https://user-images.githubusercontent.com/55928670/69642882-bce22c80-1062-11ea-9d88-64b6585d558e.png">
