### ISSUE TITLE
Specific "wake up" time for TeslaMate

### ISSUE THREAD

**Issue by brabidou** [adriankumpf/teslamate#295]
**Is your feature request related to a problem? Please describe.**
Often TeslaMate will miss drives in the morning after its been sleeping all night (I have a short commute so it'll sometimes miss the whole drive). I'm still mucking with sleep settings but cant seem to get it quite right.

**Describe the solution you'd like**
I'd like to set a time when TeslaMate should wakeup my Tesla and start polling on its normal schedule. For example, set it to wake at 7:00AM and its okay to wake the car on specific days (ie Mon-Fri). 

**Describe alternatives you've considered**
Maybe a cron job to wake TeslaMate up?

**Comment by ngardiner** [comment]
This makes a lot of sense, it is effectively a time hint option that instructs TeslaMate to resume polling during certain hours/days in lieu of a bluetooth/custom hint.

Because resuming logging does not wake the vehicle, it wouldn't be something best implemented as a once off action, but rather having TeslaMate resume polling consistently for a period of time as if the vehicle were awake, if possible having the times customizable by day of week and hour start/hour stop it would be most useful, as you could construct a set of rules that would be fairly accurate, such as resume polling between 6-8am monday to friday and 9-11am saturday and sunday to account for regular drive times. 

Whilst it wouldn't wake the vehicle from my understanding, the time period for which the time hints were active would prevent the vehicle from falling back asleep - so if you did drive for 30 mins at 6am on a monday it would pick up the start of the drive immediately, but if you had sentry off and the car was parked and locked after that, it would not fall asleep until after 8am. So there would need to be some consideration around how it was configured, but it would be fairly safe I would think?

**Comment by adriankumpf** [comment]
I don't quite understand your scenario yet. TeslaMate will notice within 60 seconds that the vehicle is awake. It does not need a a bluetooth/custom hint to resume polling. So unless your commute is _really_ short the drive should be recorded without issues. 

What could result in the drives not being recorded is the following:

1. your car wakes up in the morning (e.g. because the Tesla app has been opened)
2. it idles for a while (e.g. 15 minutes, the default 'Idle Time Before Trying to Sleep')
3. you start driving while TeslaMate has temporarily halted polling ([Time to try sleeping](https://github.com/adriankumpf/teslamate/blob/master/docs/configuration/sleep.md#time-to-try-sleeping))

In that case increasing the 'Idle Time Before Trying to Sleep' would improve things.

**Comment by brabidou** [comment]
My commute is 11 minutes door to door and it almost always misses my morning drive.  I have Time to Try Sleeping set at 15 mins and Idle Time Before Trying to Sleep set at 30 mins.

Another factor could be that I have poor cellular reception at my house and sometimes even the Tesla app struggles to connect to the Tesla.

**Comment by adriankumpf** [comment]
> Another factor could be that I have poor cellular reception at my house and sometimes even the Tesla app struggles to connect to the Tesla.

That would explain why the first part of the drive is missing. 

> Edit: Upon thinking about this more, I'll try disabling sleep mode completely just to isolate the connectivity issue vs sleep settings.

Let me know when you find out more!

**Comment by brabidou** [comment]
Been playing around with settings for a week now. If I disable Sleeping in Tesla Mate wont miss any drives but when I turn it back on I will record the drive them maybe 25% of the time.

Time to Try Sleeping: 21 mins
Idle Time Before Trying to Sleep: 15 mins

Could this have something to do with Scheduled Time to Depart charging. Car is set to depart at 8:00AM but I wonder if its not really waking up?

**Comment by adriankumpf** [comment]
You'll probably want to increase the "Idle Time Before Trying to Sleep" to 30 Minutes or more. 

To fully understand why drive data is missing check out the application logs. If polling was halted right before you start driving nothing can be logged.  In any case, using Bluetooth hints (as explained in the docs [Sleep Mode Configuration](https://github.com/adriankumpf/teslamate/blob/master/docs/configuration/sleep.md)) would solve the problem.

**Comment by brabidou** [comment]
Not sure if upgrading to latest (v1.14.1) has fixed it or I've found the right sleep settings but I seem to be capturing my morning drives now.

Current Settings:
- Time to Try Sleeping: 21mins
- Idle Time Before Trying to Sleep: 20mins
