### ISSUE TITLE
Cannot see detailed status via API for 2nd vehicle

### ISSUE THREAD

**Issue by chamsters** [adriankumpf/teslamate#3190]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I've just added a 2nd vehicle to my account, and followed guidance to log off and log back on. The car appears fine in teslamate. 

However, via API, something seems amiss. 

For car 1 I can see all sorts of data at 
http://192.168.1.xxx:xxxx/api/v1/cars/1 and
http://192.168.1.xxx:xxxx/api/v1/cars/1/status

The latter provides more info on battery SOC etc. 

For car 2: 
http://192.168.1.xxx:xxxx/api/v1/cars/2 works fine but http://192.168.1.xxx:xxxx/api/v1/cars/2/status shows "{"error":"no info on this car ID"}"

Any ideas?

### Expected Behavior

I should see detailed status of car including SOC. 

### Relevant log output

```shell
2023-04-21 18:35:09.790 [info] GET /
2023-04-21 18:35:09.792 [info] Sent 200 in 1ms
2023-04-21 18:35:10.539 [info] GET /
2023-04-21 18:35:10.540 [info] Sent 200 in 1ms
```

### Type of installation

Docker

### Version

1.27.2

**Comment by actuariat** [comment]
I have a VIN, But the car is not delivered yet. No data to cars table. I Think is not available yet.

**Comment by tobiasehlert** [comment]
Hi @chamsters,

You can close this issue, since the endpoints you are referring to are when using [TeslaMateApi](https://github.com/tobiasehlert/teslamateapi) and not native in TeslaMate.
Also I think it's no longer necessary since you had issue https://github.com/tobiasehlert/teslamateapi/issues/224 opened as well.

Regards,
Tobias
