### ISSUE TITLE
Handful of suggestions / improvements

### ISSUE THREAD

**Issue by cwanja** [adriankumpf/teslamate#339]
Hey @adriankumpf, still loving the software and appreciate all you to do improve it and implement community suggestions. Have a handful of things I have been sitting on that I wanted to suggest - like an normal good end user, right? 

- Time complete charge - any possibility to convert this from just minutes to hours & minutes. Dividing by 60 is easy, just figured since the counter for online, asleep, charging, updating, etc. is already in hours and minutes (and seconds), this could be as well.
- Grafana dashboards 24 hour time - is there a way to convert the times from 24 hour to 12 hour? 
- TeslaMate dashboard health check icons in Safari do not work in iOS. Chrome for iOS does work. Any way to resolve?

**Comment by adriankumpf** [comment]
> Time complete charge

Done! (38b86ae526a39aebab8c4ce6f40bc349848e7765)

> Grafana dashboards 24 hour time - is there a way to convert the times from 24 hour to 12 hour?

That's possible but you'd have to customize the dashboards yourself (`Column Styles -> Type -> Date Format`). The ideal solution would be to use a language sensitive representation of dates but that feature is not (yet) available in Grafana.

> TeslaMate dashboard health check icons in Safari do not work in iOS. Chrome for iOS does work. Any way to resolve?

Fixed with 3904a18e2406089b50fc2c933cfa9baf5f180704
