### ISSUE TITLE
API to retreive status and state of charge from another software

### ISSUE THREAD

**Issue by bnj04** [adriankumpf/teslamate#401]
First, thank you very much for the time and energy you put in teslamate !

**Is your feature request related to a problem? Please describe.**

I would like to be able to display status and state of charge on the domoticz dashboard.

**Describe the solution you'd like**

Be able to retreive via an API(or any other ways, json, xml, etc) the data easely parsable to feed another software

**Describe alternatives you've considered**

today, i'm using curl and a lot's of grep and sed to extract the data from the html in the homepage of teslamate. 

**Additional context**

N/A

thank you !

**Comment by tobiasehlert** [comment]
Hi @bnj04,

I think you should take a look at the [MQTT Integration](https://teslamate.readthedocs.io/en/latest/integrations/mqtt.html). This is probably exactly what you are looking for, since you can ask TeslaMate for quite some data.. you can see the topics that are available [here](https://teslamate.readthedocs.io/en/latest/integrations/mqtt.html#mqtt-topics).

On this way, you should be able to consume data from TeslaMate anywhere you want :)

Regards,
Tobias

**Comment by bnj04** [comment]
great, thank you, indeed, i'm not familiar with MQTT, i will give it a try, thank you !

**Comment by henroFall** [comment]
MQTT is the future. Essential middleware for anything to talk to anything.
Very useful to learn about and very shallow learning curve. Well worth your
time.

**Comment by bnj04** [comment]
I tried and it was very easy to get data from cli :

mosquitto_sub -h servername -t teslamate/cars/1/state -C 1

thank you !
