### ISSUE TITLE
How to? 2 or more users?

### ISSUE THREAD

**Issue by detritu5** [adriankumpf/teslamate#403]
Is there any posibility to create one or more dockers each user?
I want to add some friends stats to my NAS, but I tried to make 2 differents dockers only changing ports and didn´t work.
How can I test another users with his car?

**Comment by tobiasehlert** [comment]
I tried around myself earlier and ended up with running one vmware host per TeslaMate installation.. but with that you will end up with a couple of different servers running at the same time (since I host this at home for a couple of friends).

Following thread to see if someone else has a good suggestion for you :)

**Comment by tobiasehlert** [comment]
On [issue 180](https://github.com/adriankumpf/teslamate/issues/180#issuecomment-537700455) @adriankumpf mentioned:
that you basically need to extend the docker-compose file to have two teslamate and two postgres services. Then expose both on different (sub)domains., and you should be up and running.

@adriankumpf what about the MQTT as well, shouldn't there be a separate one per instance as well?

One thing that I faced trying this was, that I needed to have two grafana services as well, since the [datasource.yml](https://github.com/adriankumpf/teslamate/blob/master/grafana/datasource.yml) environment flags are only set for one environment (which maps to one service at a time).
So you will have then in total have two teslamate, two postgres and two grafana services running at the same time, so basically you just duplicate all the whole setup and adjust all the volumes and parameters that need to be adjusted.

**Why not run one Grafana for all my TeslaMate installations?**
The way around there would maybe be to create a single Grafana instance and manually add connection details to your different datasources manually and adjust all the dashboard to work properly. But that will be a hassle to update when new versions are released.. so I guess this is no way forward for you either. Going for organisations in Grafana will not be a solution either, since even if you define different Default datasources for each organisation, you still have to do manual labor when updating, since dashboards are not synced/shared between organisations.

**Comment by spacecosmos** [comment]
I also like to know how to set up a multi-user environment. Would like to add more users and cars.

**Comment by tobiasehlert** [comment]
@spacecosmos, on [issue 180](https://github.com/adriankumpf/teslamate/issues/180#issuecomment-537722451) @adriankumpf said:

> The thing is, implementing a multi-user system is quite complex and only useful for very few people. I'd rather spend my time doing something else tbh :)

He has to answer on the question, if he might change his mind. :)

**Comment by adriankumpf** [comment]
I would suggest the following:

- Use one `teslamate` instance per Tesla account
- Use a single Postgres instance with a separate database for each teslamate instance
- Use a single MQTT Broker

> @adriankumpf what about the MQTT as well, shouldn't there be a separate one per instance as well?

It's possible to share an MQTT broker by setting the `MQTT_NAMESPACE` environment variable for each TeslaMate instance.

> @spacecosmos, on issue 180 @adriankumpf said:

> The thing is, implementing a multi-user system is quite complex and only useful for very few people. I'd rather spend my time doing something else tbh :)

> He has to answer on the question, if he might change his mind. :)

I'm afraid not. Native multi-tenancy support goes beyond the scope of this project.

**Comment by Dustin781** [comment]
how do i install a second instance? 

do u have docker-comose.yml for this? 
i think, just changing the ports are not working, because the name is the same and when i chance the DB Port 1883 the teslamate wouldn't found the database?

**Comment by kongomongo** [comment]
@Dustin781 I tried to modify my yml file as per @adriankumpf's suggestion but was unable to do it with a single postgres instance because I did not know how to specify multiple POSTGRES_DB environments in the database service.

within section services I simply duplicated:
```
teslamate -> teslamate2 (change within ports setting: 4000:4000 to 4001:4000 (so that it is accessible on the outside on port 4001)), change DATABASE_HOST from database to database2
database -> database2 (change volumes from teslamate-db to teslamate2-db, change POSTGRES_DB from teslamate to teslamate2)
grafana -> grafana2 (change DATABASE_HOST from database to database2, change within ports setting: 3000:3000 to 3001:3000 (so that it is accessible on the outside on port 3001), change volumes from teslamate-grafana-data to teslamate2-grafana-data)
```

within section volumes I added:
```
teslamate2-db
teslamate2-grafana-data
```

It works, however I'm no expert.
