### ISSUE TITLE
Consider using the websocket streaming API

### ISSUE THREAD

**Issue by Niek** [adriankumpf/teslamate#417]
Right now Teslamate polls the Tesla API by calling ``/api/1/vehicles/#{id}/vehicle_data`` regularly. Wouldn't it be better to use the streaming websocket API instead?

Advantages would be:
* Instantaneous updates of car data (around once per second) - no polling delays
* No waking up in case the car is sleeping (not 100% sure about this though - but it seems to be the case in my tests)
* More future-proof, since the Tesla app also seems to be abandoning the polling method

Some code samples:
https://github.com/timdorr/tesla-api/blob/master/lib/tesla_api/stream.rb
https://github.com/mseminatore/TeslaJS/pull/158/files#diff-8cc7128b6d8cb9a5b8a5fbdc3dd86338

**Comment by bahree** [comment]
From my understanding, the streaming thing is old and hasnt been working for a while and we can't seem to figure out, how to use it. Unless this changed recently - I hadn't looked at it for some time now. 
We can also see how it is [empty here](https://tesla-api.timdorr.com/vehicle/streaming) for now and eve when reverse engineering some of the code from the app.

**Comment by Niek** [comment]
I agree the documentation is sparse, but it's working fine in my experience. See the second link I posted for the PR where I added support for it to TeslaJS. My Elixir experience is very little but I'be be more than happy to help implement it in Teslamate.

**Comment by Niek** [comment]
I did some tests, while the websocket API is only good to get basic stats (heading/lat/long/odo/power/range/speed/soc) it is actually very useful to check the car status without waking up the car. The current Teslamate sleep mode could be improved a lot by using a hybrid of the websocket API and the regular polling API:

- Instead of the "falling asleep" stage, we can continue to monitor the car by watching the websocket while it's parked
- This allows the car to fall asleep quicker (no more idle timer) and we don't miss up to 21 mins of driving because of halted polling
- Once the car is asleep, we can use the websocket to notified immediately once the car starts driving - so you don't miss up to 30 secs of driving

Once driving, we could also use the realtime websocket data to store frequent basic position data and poll the rest of the data (climate/fan/settings/etc) once a minute or so - this will eliminate a lot of load from the API.

**Comment by adriankumpf** [comment]
That sounds very promising! I like the idea. 

Is the WebSocket API supported by all vehicles and hardware generations? After reading timdorr/tesla-api/issues/97 I'm also not sure how reliable the streaming API works. What is your experience with it?

**Comment by Niek** [comment]
The ``wss://streaming.vn.teslamotors.com/streaming/`` endpoint seems to be working fine for me, but I only have a M3 to test it against. Looking at the Android app source this should work across all models though.

**Comment by adriankumpf** [comment]
Okay, I'm also gonna run some tests, also with an M3.

**Comment by adriankumpf** [comment]
🎉 Now available on master: `Settings -> Streaming API -> Enable`.  It works pretty damn good, at least with the M3. I don't know yet how the other models compare.

**Comment by Niek** [comment]
Awesome job! Will test it and let you know my experience

**Comment by adriankumpf** [comment]
Let me know if you notice anything. The "Idle Time Before Trying to Sleep" settings can be lowered to 3 minutes when using the Streaming API.

**Comment by Niek** [comment]
Works great for me! 👍🏻

**Comment by LelandSindt** [comment]
pulled, built, deployed, testing.. (model 3)

How does "Time to Try Sleeping" come into play with streaming enabled?

**Comment by adriankumpf** [comment]
> Works great for me! 👍🏻

Perfect! Now all that is needed are a few more testers (with different models) before the streaming API can be enabled by default.

**Comment by adriankumpf** [comment]
> How does "Time to Try Sleeping" come into play with streaming enabled?

This setting is then redundant since polling continues while the car falls asleep.

**Comment by timdodge** [comment]
It's also working well for me (Model 3, master from 28/03 and manual install on a gentoo server).
Thanks.

**Comment by ArnoPW** [comment]
How can I try this? Simply docker-compose pull or another method?

**Comment by SigLinJo** [comment]
I have built v1.19.0-dev in an instant tracking a Model S 75. Sounds as a really good update, specifically for these older MCU1 cars that I have not managed to get Sleep mode worked to with! Installed and started logging successfully, will update here how it goes when some trips are logged.

**Comment by adriankumpf** [comment]
> How can I try this? Simply docker-compose pull or another method?

I've pushed a dev release to DockerHub. To use it, change the following lines in the docker-compose.yml:

```YAML
    image: teslamate/teslamate:1.19.0-dev

# ...

    image: teslamate/grafana:1.19.0-dev
```

Note, however, that this update changes the database schema, so downgrading to v1.18 would require some manual effort. Upgrading to the final v1.19 release will be straight-forward though.

**Comment by ograff** [comment]
I figured I'd give this a shot using the dev docker image. I got the following handful of messages during "Falling Asleep" in the console:

```
teslamate_1  | 18:52:58.845 [info] Stream.Timeout / 0
teslamate_1  | 18:53:09.298 [info] Stream.Timeout / 1
teslamate_1  | 18:53:19.758 [info] Stream.Timeout / 2
teslamate_1  | 18:56:14.727 [info] Stream.Timeout / 0
teslamate_1  | 18:58:10.956 [info] Stream.Timeout / 0
teslamate_1  | 18:58:21.390 [info] Stream.Timeout / 1
teslamate_1  | 18:59:14.877 [info] GET /
teslamate_1  | 18:59:14.881 [info] Sent 200 in 4ms
teslamate_1  | 18:59:30.285 [info] Stream.Timeout / 0
```

Is there any way to make the log level include debug statements? Would that be useful?

**Comment by SigLinJo** [comment]
I have gotten a couple of drives logged with the Streaming API version of Teslamate now and have some observations:

The cars (one S 85 from 2014 with newly replaced MCUv1 running 2020.8.1.1 and one S 75 from 2016 running 2020.8.2) manage to go to sleep now which they didn't when I used the old polling version. But the S 75 shows some strange logging of temperatures, SOC and range... I also include logs for both instances from the screen session. I don't know if there are any more logs you would like to see.

Some screenshots:

S 85:
States
![S 85 states](https://user-images.githubusercontent.com/19478141/78071475-e0650d00-739d-11ea-8194-ddb2f2e43dc6.png)

Drive
![S 85 drive](https://user-images.githubusercontent.com/19478141/78071488-e955de80-739d-11ea-9618-775708015d3d.png)

Log
[1.19.0-dev on S 85 with newly replaced MCU.txt](https://github.com/adriankumpf/teslamate/files/4411414/1.19.0-dev.on.S.85.with.newly.replaced.MCU.txt)

S75:
States
![S 75 states](https://user-images.githubusercontent.com/19478141/78071521-ff639f00-739d-11ea-8b65-9a5e17f6f9e2.png)

Short and long drives with strange logging and long drive with normal logging
![S 75 drive](https://user-images.githubusercontent.com/19478141/78071620-20c48b00-739e-11ea-8439-47b44124fa1a.png)
![S 75 longer drive](https://user-images.githubusercontent.com/19478141/78071633-23bf7b80-739e-11ea-8911-747ee6c6da7d.png)
![S 75 normal drive](https://user-images.githubusercontent.com/19478141/78071707-3df95980-739e-11ea-93c8-8f465f06bb4d.png)

Strange elevation and temperature logging
![S 75 strange elevation and temperature](https://user-images.githubusercontent.com/19478141/78071730-43ef3a80-739e-11ea-9b6f-fef18c80c330.png)

Log
[1.19.0-dev on S 75 with MCU from 2016.txt](https://github.com/adriankumpf/teslamate/files/4411435/1.19.0-dev.on.S.75.with.MCU.from.2016.txt)


It works but the strange logging on some of the S 75 drives is not optimal and at least one of the S 75 drives still started logging a couple of hundred meters from the start of the trip.

I am running Teslamate on FreeBSD in jails so not the standard Docker solution...

Just let me know if you are interested of any other data. So far very promising :)

**Comment by SigLinJo** [comment]
Dug a little deeper and projected range is going bananas for the S 75:

![S 75 projected range](https://user-images.githubusercontent.com/19478141/78075579-1954b000-73a5-11ea-8477-f515f0419e93.png)

While the S 85 is looking normal:
![S 85 projected range](https://user-images.githubusercontent.com/19478141/78075621-2a9dbc80-73a5-11ea-879d-49ed656248ff.png)

Maybe correlated with the strange logging for the S 75 ?

**Comment by adriankumpf** [comment]
> The cars (one S 85 from 2014 with newly replaced MCUv1 running 2020.8.1.1 and one S 75 from 2016 running 2020.8.2) manage to go to sleep now which they didn't when I used the old polling version. But the S 75 shows some strange logging of temperatures, SOC and range... I also include logs for both instances from the screen session. I don't know if there are any more logs you would like to see.

Thanks for the quick response.  It is very useful to see both MCUs in action!

> It works but the strange logging on some of the S 75 drives is not optimal and at least one of the S 75 drives still started logging a couple of hundred meters from the start of the trip.

From what I can tell, it actually seems to work fine :) You just need to update/re-import your dashboards. Background: The continuous lines are streamed data. The single dots are data from the regular polling-based API, which is still used (but less frequently). The updated dashboards adjust some settings so that Grafana still shows continuous lines.

Regarding the delayed trip logging: please keep an eye on that. If this happens regularly, I'd be interested in the data. But it was probably just a hiccup on the API side.

Based on your logs I could also identify a bug in the connection handling. So please pull the latest changes, if possible.

**Comment by SigLinJo** [comment]
Just as a quick response: I pulled the latest master and rebuilt both instances. Still getting some connection errors in the logs, will send new ones when some more time has passed. One is that I get a lot of these:
`18:37:28.904 [warn] Disconnected! Connection Error: Could not resolve domain name. | 227703
18:37:28.906 [warn] Disconnected! Connection Error: Could not resolve domain name. | 227704
18:37:28.909 [warn] Disconnected! Connection Error: Could not resolve domain name. | 227705
18:37:28.911 [warn] Disconnected! Connection Error: Could not resolve domain name. | 227706
18:37:28.914 [warn] Disconnected! Connection Error: Could not resolve domain name. | 227707
18:37:28.917 [warn] Disconnected! Connection Error: Could not resolve domain name. | 227708
18:37:28.919 [warn] Disconnected! Connection Error: Could not resolve domain name. | 227709
18:37:28.922 [warn] Disconnected! Connection Error: Could not resolve domain name. | 227710
18:37:28.924 [warn] Disconnected! Connection Error: Could not resolve domain name. | 227711
18:37:28.929 [warn] Disconnected! Connection Error: Could not resolve domain name. | 227712
18:37:28.932 [warn] Disconnected! Connection Error: Could not resolve domain name. | 227713
18:37:28.936 [warn] Disconnected! Connection Error: Could not resolve domain name. | 227714
18:37:28.940 [warn] Disconnected! Connection Error: Could not resolve domain name. | 227715
18:37:28.942 [warn] Disconnected! Connection Error: Could not resolve domain name. | 227716
18:37:28.948 [warn] Disconnected! Connection Error: Could not resolve domain name. | 227717
18:37:28.951 [warn] Disconnected! Connection Error: Could not resolve domain name. | 227718`
They scroll down the screen very fast, as you can see by the very short time between the timestamps and the high number of instances of the error...

I found the problem with my dashboards. the bash script had been updated from source and the admin password had been reset to default and then even if I ran the script no update of the dashboards where made :) Projected range and drive details looks good again!

Keep up the good work! I really like Teslamate and hope to be able to provide help with making it better! Not so good at programming thou, just googling and trying my best at configuring this. I might have done something in my reverse proxies or firewall that interferes and causes the connection errors?

**Comment by adriankumpf** [comment]
I have pushed a fix so that fewer errors of that kind will be printed in a short time.

The above log files contain similar errors. Maybe a problem with your DNS server?

**Comment by SigLinJo** [comment]
I will look into my DNS. Running PfSense and have been following some guides to strengthen security, maybe have gone to far? Will dig into the logs in the firewall! Thank you for the fix, will rebuild now :)

**Comment by SigLinJo** [comment]
As an update a couple of days later after running Streaming API in two older model S I can only say that it is really nice. Trips are picked up straight away and with good resolution from the beginning. Only had one trip that lost a couple of blocks of initial driving.

Also had stretches on with both cars that had lower logging resolution from position, power and so on. Not unusable, but for one of the drives there where roughly 5 minutes with time resolution ranging between 35 seconds and 10 seconds. This started 1 minute in to the drive after a really impressive correct logging of the drive in an underground parking garage. The slower logging started when the car was about to exit the parking garage. Maybe the car had bad reception? State is showing as offline leading up to the drive, but with a short online before the drive starts?

Overall, Streaming API looks so good I'm tempted to bring my model 3 SR+ up to it even if its only beta right now :) With Streaming API the need for waking up the car with Tasker and so on goes away and it makes Teslamate really awesome! Have missed some drives due to my car trying to sleep and Tasker wakeup failing to work, always made me sad. Hopefully that will be lot less of a problem now!

**Comment by adriankumpf** [comment]
> Also had stretches on with both cars that had lower logging resolution from position, power and so on. Not unusable, but for one of the drives there where roughly 5 minutes with time resolution ranging between 35 seconds and 10 seconds. This started 1 minute in to the drive after a really impressive correct logging of the drive in an underground parking garage. The slower logging started when the car was about to exit the parking garage. Maybe the car had bad reception? State is showing as offline leading up to the drive, but with a short online before the drive starts?

If the resolution of those drives has improved while driving, not much can be done.  It sounds a lot like bad reception. The logs for those drives would be interesting though.

> Overall, Streaming API looks so good I'm tempted to bring my model 3 SR+ up to it even if its only beta right now :) With Streaming API the need for waking up the car with Tasker and so on goes away and it makes Teslamate really awesome! Have missed some drives due to my car trying to sleep and Tasker wakeup failing to work, always made me sad. Hopefully that will be lot less of a problem now!

Yeah, this problem should be a thing of the past! :) It's still in beta, but we are close to release. There will only be a few more bug fixes that have nothing to do with streaming.

**Comment by Dulanic** [comment]
Love this! Just need to watch for our ever growing databases bases now :) It looks like we get a update every ~1/2 second vs every 5 seconds. It shouldn't make it MASSIVE, but I did have 60MB table after 2 months /w the old ratio, so that would had been 500MBish /w the new method for 2 months.

`SELECT date_trunc('minute', DATE), COUNT(*)
FROM positions
WHERE DATE >= '2020-04-06'
GROUP BY date_trunc('minute', DATE)
HAVING COUNT(*) > 3
ORDER BY 1 DESC
`

"2020-04-07 16:05:00"	"18"
"2020-04-07 16:06:00"	"20"
"2020-04-07 16:07:00"	"21"
"2020-04-07 16:08:00"	"21"
"2020-04-07 16:09:00"	"21"
"2020-04-07 16:10:00"	"21"
"2020-04-07 16:11:00"	"21"
"2020-04-07 16:12:00"	"21"
"2020-04-07 16:13:00"	"22"
"2020-04-07 16:14:00"	"21"
"2020-04-07 16:15:00"	"20"
"2020-04-07 16:16:00"	"21"
"2020-04-07 16:17:00"	"14"
"2020-04-07 19:39:00"	"18"
"2020-04-07 19:40:00"	"21"
"2020-04-07 19:41:00"	"21"
"2020-04-07 19:42:00"	"21"
"2020-04-07 19:43:00"	"21"
"2020-04-07 19:44:00"	"14"
"2020-04-07 20:13:00"	"20"
"2020-04-07 20:14:00"	"21"
"2020-04-07 20:15:00"	"21"
"2020-04-07 20:16:00"	"21"
"2020-04-07 20:17:00"	"20"
"2020-04-07 20:18:00"	"21"
"2020-04-08 12:52:00"	"22"
"2020-04-08 12:53:00"	"21"
"2020-04-08 12:54:00"	"21"
"2020-04-08 12:55:00"	"21"
"2020-04-08 12:56:00"	"21"
"2020-04-08 12:57:00"	"21"
"2020-04-08 12:58:00"	"20"
"2020-04-08 12:59:00"	"5"
"2020-04-08 13:12:00"	"20"
"2020-04-08 13:13:00"	"20"
"2020-04-08 13:14:00"	"21"
"2020-04-08 13:15:00"	"21"
"2020-04-08 13:16:00"	"20"
"2020-04-08 13:17:00"	"21"
"2020-04-08 13:18:00"	"21"
"2020-04-08 13:19:00"	"20"
"2020-04-08 13:20:00"	"7"
"2020-04-08 15:26:00"	"130"
"2020-04-08 15:27:00"	"185"
"2020-04-08 15:28:00"	"133"
"2020-04-08 15:29:00"	"206"
"2020-04-08 15:30:00"	"176"
"2020-04-08 15:31:00"	"183"
"2020-04-08 15:32:00"	"183"
"2020-04-08 15:33:00"	"126"
"2020-04-08 16:38:00"	"50"
"2020-04-08 16:39:00"	"198"
"2020-04-08 16:40:00"	"214"
"2020-04-08 16:41:00"	"207"
"2020-04-08 16:42:00"	"201"
"2020-04-08 16:43:00"	"167"
"2020-04-08 16:44:00"	"180"
"2020-04-08 16:45:00"	"141"
"2020-04-08 16:46:00"	"194"
"2020-04-08 16:47:00"	"152"

**Comment by bahree** [comment]
So I am curious - this adds a lot of 'strain' given higher frequency - or so it seems; so the question I go in my head is why? what does it solve?

**Comment by ngardiner** [comment]
That would be an assumption @bahree - given this is passive consumption of a higher frequency data stream rather than active polling, it likely reduces rather than increases overhead in every regard other than the data storage (which frankly is what most of us are using this project for). The benefits of this are passive polling without unnecessary data loss due to complex polling methodology and higher precision drive data.

**Comment by Niek** [comment]
Data storage is cheap, I don't see an issue with increasing the storage usage. The benefits outweigh this massively: higher precision, proper sleeping mode (as the only Tesla logging app out there, actually) and massive reduction of strain on the Tesla API (thereby solving issues like #464).

**Comment by Dominoo** [comment]
I agree that data storage is cheap these days, however having 130 records of position per minute seems like an overkill to me. Maybe consideration might be "log reduction" for older entries. with approximation / averaging each 10 records?

**Comment by Dulanic** [comment]
With the updates made for https://github.com/adriankumpf/teslamate/commit/45d94d52b381f9183bdc6de1995f2c94c481b794 I feel pretty good with the storage now. I an running pghero to monitor performance and will track further. The amount isn't stressful, and with the smaller field sizes, it should be good.

**Comment by bahree** [comment]
Storage might be cheap, but many folks run this on a pi, and there are issues on read/write cycles on SD cards. So just because we can, doesn't mean we should. Just my $0.02 :). I think throttling this down to some subset would be better in the longer run.

**Comment by SigLinJo** [comment]
If it's throttled please make it optional. I run Teslamate on FreeNAS with 20 TB of storage available in a file system that can handle the writes and to have the high resolution for speed, position and power is really nice. With so many data points logged we could record launches and stuff like that if we are lucky, and have higher chance of actually logging peak power events. You travel ca 30 m/s at 110 km/h so 3 positions per second at that speed still have 10 meter between them :) I think Tesla has made a good choice for their streaming resolution. But i can understand if some want to limit the logging to not strain their system so an optional reduction could maybe be useful.

**Comment by Dulanic** [comment]
Seems like 1.19dev is having issues? I was able to go back to latest w/o streaming and it functions OK, but 1.19 keeps failing.

```
Request: GET /


** (exit) an exception was raised:


    ** (ArithmeticError) bad argument in arithmetic expression


        :erlang.*(#Decimal<18.5>, 9)


        (teslamate 1.19.0-dev) lib/teslamate/convert.ex:27: TeslaMate.Convert.celsius_to_fahrenheit/2


        (teslamate 1.19.0-dev) lib/teslamate_web/templates/car/summary.html.leex:241: anonymous fn/2 in TeslaMateWeb.CarView."summary.html"/1


        (phoenix_live_view 0.11.1) lib/phoenix_live_view/diff.ex:221: Phoenix.LiveView.Diff.traverse/5


        (phoenix_live_view 0.11.1) lib/phoenix_live_view/diff.ex:288: anonymous fn/3 in Phoenix.LiveView.Diff.traverse_dynamic/5


        (elixir 1.10.2) lib/enum.ex:2111: Enum."-reduce/3-lists^foldl/2-0-"/3


        (phoenix_live_view 0.11.1) lib/phoenix_live_view/diff.ex:221: Phoenix.LiveView.Diff.traverse/5


        (phoenix_live_view 0.11.1) lib/phoenix_live_view/diff.ex:288: anonymous fn/3 in Phoenix.LiveView.Diff.traverse_dynamic/5
```
