### ISSUE TITLE
Advanced setup using one FQDN

### ISSUE THREAD

**Issue by bastrik** [adriankumpf/teslamate#419]
Hello all,

I followed the `Advanced Docker Setup with Traefik` and have been trying to get it running on an Azure VM. However, due to the VM limitation, it can only provide one FQDN per VM.

I played around with the docker-compose.yml files and tried to setup `VIRTUAL_HOST` to a path on the FQDN (123.example.com/home)  and changed the router rule to 
`traefik.http.routers.teslamate.rule=Host(``${FQDN_TM}``) && PathPrefix(``/home``)`, 
and in the logs I can see `Access TeslaMateWeb.Endpoint at http://123.example.com/home`

When I go to the site, I am prompted to login, but after I log in, I see a `Not Found` error, and the log shows 
>teslamate_1  |20:28:38.443 [info] GET /home
teslamate_1  | 20:28:38.443 [info] Sent 404 in 225µs
teslamate_1  | 20:28:38.444 [info] Converted error Phoenix.Router.NoRouteError to 404 response

I wonder if I need to add additional labels in traefik rules to make this work? Thank you for you help!

**Comment by MostDefiantly** [comment]
@bastrik I was able to get two FQDN's pointed to one VM in azure via powershell. When I get home, I'll see if I still have my notes - maybe they will be helpful.

**Comment by MostDefiantly** [comment]
@bastrik Here's the guide I used to create multiple PublicIP's routed to multiple PrivateIP's on the same Azure VM:

https://docs.microsoft.com/en-us/azure/virtual-network/virtual-network-multiple-ip-addresses-powershell

Some gotchas, may be obvious but worth calling out since the guide is assuming a Windows VM:

- Using Linux, you would open port 24 for SSH - not 3389 for RDP
- You essentially create two publicIP's in Azure, and map them to discreet PrivateIP's in Azure. On the VM, you'll manually assign both PrivateIP's by editing the eth0 config.
- When all is said and done you'll have two FQDN's both pointed at the same TeslaMate install. 

Hope that helps!

**Comment by bastrik** [comment]
Thanks for the doc! Confirming that this did the trick.

Marking this as closed.
