### ISSUE TITLE
'Unit' seems to stay as km even with mi selected in settings

### ISSUE THREAD

**Issue by bpankz** [adriankumpf/teslamate#431]
**Describe the bug**

Some drives are showing distance and speed in KM instead of miles when clicking through to the drive-details dashboard. Unit is set to mi in settings.

**To Reproduce**

1. Go to 'Drives'
2. Click on the timestamp of the drive to be taken to the drive-details dashboard
3. Distance is always in km, speed is in km/h
It did show as miles once until clicking back to Drives and then going back to the same drive drive-details page it displayed km

**Expected behavior**

Unit should follow the settings

**Screenshots**

![image](https://user-images.githubusercontent.com/54423181/74078417-09999a80-49f8-11ea-8072-88dccfa02f4a.png)

**Operating environment**

- TeslaMate Version: v1.16
- Type of installation: Manual
- OS: Ubuntu Server

**Comment by bpankz** [comment]
also attaching new drive-details screenshot for the racetrack example in the screenshot examples section so it's consistent with the new dashboard style
![racetrack](https://user-images.githubusercontent.com/54423181/74078445-8c225a00-49f8-11ea-9929-58460f64ccd9.png)

**Comment by bpankz** [comment]
maybe it's grafana? i'm using 6.6.11. I'll try downgrading later but temps also show as Celsius.

**Comment by adriankumpf** [comment]
That's strange. The settings are refreshed on dashboard load. What's shown if you open the dashboard directly?

**Comment by adriankumpf** [comment]
> also attaching new drive-details screenshot for the racetrack example in the screenshot examples section so it's consistent with the new dashboard style
> ![racetrack](https://user-images.githubusercontent.com/54423181/74078445-8c225a00-49f8-11ea-9929-58460f64ccd9.png)

Thank you!

**Comment by bpankz** [comment]
Opening Drive Details directly shows miles all the time. Tried chrome, chrome beta, edge, they all showed miles for the very first time and then clicking Drives ->single drive, it switched back to km. Charges also show celsius. I'll try clearing caches and see if that helps, maybe recheck out and compile teslamate

**Comment by bpankz** [comment]
yup it's definitely grafana 6.6.1. Downgraded to 6.5.3 and everything is working.

**Comment by adriankumpf** [comment]
It seems to be related to this issue: Grafana/grafana#21895

**Comment by gaLDWoRE** [comment]
I just setup TeslaMate through simple install via Docker and once I changed it to Miles and Fahrenheit it seems to work without issues. Don't know if browser matters, but I'm using Firefox. Oh and I'm on Win10. 
The only thing that's not showing are the actual figures in those three boxes, it just says mi, but the graphs show all the data. I'm assuming that the boxes may need more time to actually populate the data, since I just started using this.

**Comment by bpankz** [comment]
still happening with grafana 6.6.2. is the workaround to not pass variables "between" dashboards like that grafana bug report says? doesn't look like i'm losing anything feature wise so I'll downgrade back to 6.5.3 for the time being

**Comment by brad07x** [comment]
I'm seeing this behavior as well. 

For me, it is impacting the length_unit, temperature_unit, and car_id variables on the following dashboards:
Internal -> Drive Details
Internal -> Charge Details

The car_id variable being incorrect is a pain in particular as it causes the details dashboards to always try to load drive data for the first car_id (1) in my account instead of the appropriate drive I selected from the 'Drives' dash (2).

I can temporarily fix the units by adjusting the variables in the URL as needed:
i.e. ...'&var-temp_unit=F&var-length_unit=mi&var-car_id=2'... but this is not persistent.

While viewing the list of drives or charges from these respective dashboards in the Teslamate folder, the distance units are displayed correctly.

Running teslamate v1.17.1 release under docker using the advanced setup guide. 

Began to observe this issue following the upgrade to v1.17.1 & Grafana v6.6.2 from the previous version (1.14.3).
Grafana v6.6.2 (3fa63cfc34)

**Comment by adriankumpf** [comment]
Seems to be fixed in Grafana v7.0
