### ISSUE TITLE
Drive information missing

### ISSUE THREAD

**Issue by natrlhy** [adriankumpf/teslamate#436]
![Annotation 2020-02-10 095729](https://user-images.githubusercontent.com/19696424/74176038-c4d65500-4beb-11ea-903a-a8114de19831.png)

Noticed that recent drives are showing up like this. Is there any way to correct this?
How do I dig deeper into this?

TeslaMate v 1.16
Install Type: Synology

**Comment by ArnoPW** [comment]
Not exactly the same, but I see this (especially the Consumption and Efficiency are not always "available").

![image](https://user-images.githubusercontent.com/52374663/74235916-5e773280-4cd0-11ea-944a-ea1bb8a2430b.png)

**Comment by adriankumpf** [comment]
The [bug report template](https://github.com/adriankumpf/teslamate/issues/new?assignees=&labels=&template=bug_report.md&title=) lists the necessary steps to dig deeper into this. Please edit the description of your issue and add this information.

> Is there any way to correct this?

See [Manually fixing data: Delete a specific drive](https://teslamate.readthedocs.io/en/latest/maintenance/manually_fixing_data.html)

**Comment by MostDefiantly** [comment]
@ArnoPW I have noticed the same in both behaviors. 

- Long drives with no efficiency
- A 30 minute commute stopping within a minute for no reason

Perhaps some fragility with the TeslaAPI? I'll submit logs and add them to the thread when I get a chance.

**Comment by bjnhg-g** [comment]
![image](https://user-images.githubusercontent.com/61028952/74482521-f7ff3980-4eb4-11ea-95ba-1ffbfb4bb488.png)

I've only extracted today's data from positions table ...
[positions.csv.txt](https://github.com/adriankumpf/teslamate/files/4201478/positions.csv.txt)
=>> ? drive_id empty ?
=>> Nothing special during the affected drives, except the car has lost the network for many minutes because of bad data covering and borders crossing ...
I do not have the teslamate logs.

TeslaMate v 1.16
Install : Manual

**Comment by MostDefiantly** [comment]
@adriankumpf It looks like API issues may be contributing to blank Consumption and Efficiency? Or is that a red herring perhaps. 

**Describe the bug**

Consumption and Efficiency missing from drives where it would be expected to be calculated.

**To Reproduce**

Drive, look at the Drive manifest, see no Consumption or Efficiency.

**Expected behavior**

Consumption and Efficiency to be calculated on drives greater than a couple minutes.

**Relevant entries from the logs**

teslamate_1  | 20:59:47.655 car_id=1 [info] Charging / SOC: 57% / Home
teslamate_1  | 02:20:24.922 [info] Adding elevation to 1 positions ...
teslamate_1  | 11:31:01.347 car_id=1 [info] Derived efficiency factor: 131.25 Wh/km (88x confirmed)
teslamate_1  | 11:31:01.347 car_id=1 [info] Charging / Complete / 17.06 kWh – 871 min
teslamate_1  | 11:31:01.347 car_id=1 [info] Start / :online
teslamate_1  | 12:56:57.910 car_id=1 [info] Charging / SOC: 90% / Home
teslamate_1  | 13:02:51.400 car_id=1 [info] Derived efficiency factor: 131.25 Wh/km (88x confirmed)
teslamate_1  | 13:02:51.401 car_id=1 [info] Charging / Complete / 0.09999999999999787 kWh – 6 min
teslamate_1  | 13:02:51.401 car_id=1 [info] Start / :online
teslamate_1  | 14:20:31.015 [info] Adding elevation to 1 positions ...
teslamate_1  | 14:27:51.469 car_id=1 [info] Charging / SOC: 89% / Home
teslamate_1  | 14:38:35.937 car_id=1 [info] Derived efficiency factor: 131.25 Wh/km (88x confirmed)
teslamate_1  | 14:38:35.937 car_id=1 [info] Charging / Complete / 0.11000000000000298 kWh – 11 min
teslamate_1  | 14:38:35.937 car_id=1 [info] Start / :online
teslamate_1  | 14:51:47.726 car_id=1 [info] Charging / SOC: 89% / Home
teslamate_1  | 15:08:41.409 car_id=1 [info] Derived efficiency factor: 131.25 Wh/km (88x confirmed)
teslamate_1  | 15:08:41.409 car_id=1 [info] Charging / Disconnected /  kWh – 17 min
teslamate_1  | 15:08:41.409 car_id=1 [info] Start / :online
teslamate_1  | 15:09:42.094 [error] TeslaApi.Error / 504 – %{"error" => "upstream_timeout", "error_description" => "", "response" => nil}
teslamate_1  | 15:09:42.094 car_id=1 [error] Error / :timeout
teslamate_1  | 15:10:07.147 [error] TeslaApi.Error / 504 – %{"error" => "upstream_timeout", "error_description" => "", "response" => nil}
teslamate_1  | 15:10:07.147 car_id=1 [error] Error / :timeout
teslamate_1  | 15:10:22.620 car_id=1 [info] Driving / Start
teslamate_1  | 15:10:35.960 [error] TeslaApi.Error / 504 – %{"error" => "upstream_timeout", "error_description" => "", "response" => nil}
teslamate_1  | 15:10:35.960 car_id=1 [error] Error / :timeout
teslamate_1  | 15:10:50.845 [error] TeslaApi.Error / 504 – %{"error" => "upstream_timeout", "error_description" => "", "response" => nil}
teslamate_1  | 15:10:50.845 car_id=1 [error] Error / :timeout
teslamate_1  | 15:11:06.260 [error] TeslaApi.Error / 504 – %{"error" => "upstream_timeout", "error_description" => "", "response" => nil}
teslamate_1  | 15:11:06.260 car_id=1 [error] Error / :timeout
teslamate_1  | 15:11:20.240 [error] TeslaApi.Error / 504 – %{"error" => "upstream_timeout", "error_description" => "", "response" => nil}
teslamate_1  | 15:11:20.240 car_id=1 [error] Error / :timeout
teslamate_1  | 15:37:08.750 car_id=1 [info] Driving / Ended / 18 km – 27 min
teslamate_1  | 15:37:08.750 car_id=1 [info] Start / :online

**Screenshots**

![image](https://user-images.githubusercontent.com/11999981/75902788-720c4980-5df5-11ea-8f3b-0a1e7eee7563.png)


**Data**

See Attachments.

[Drive_Data.zip](https://github.com/adriankumpf/teslamate/files/4288594/Drive_Data.zip)

**Operating environment**

- TeslaMate Version: 1.17.1
- Type of installation: Docker
- OS: Ubuntu 18.04.4 LTS

**Comment by adriankumpf** [comment]
The consumption values are estimated by TeslaMate itself. If those values cannot not be determined accurately, e.g. because a drive is too short or because of cold weather (reduced range), they are no longer displayed starting with v1.15. For more information please see #390.
