### ISSUE TITLE
Add missing drive position data from GPX file?

### ISSUE THREAD

**Issue by khorton** [adriankumpf/teslamate#474]
We did a drive recently where the car lost cell coverage for a long period.  If you look at the map for that drive, there is a straight line that spans the period with missing data.  Is there a way to manually add the missing position, elevation and speed vs time data from a GPX file?

**Comment by adriankumpf** [comment]
A direct import from a GPX file is not supported. In order to add missing positions you would need to manually insert data into the `positions` table.

**Comment by gpsbabel** [comment]
Not to butt in, but you can use GPSBabel to read the GPX. Use the interpolate filter to break that straight line into smaller ones based on times and locations of the endpoints. (It won't snap those to roads.) Use the height filter to add missing elevation.  The end result may or may not really be better than just accepting the original. 

Instead of writing the result back to GPX, write it to unicsv where you can probably import it into positions or write a custom style that is "insert into positions" lines and just build it up to the SQL syntax to do the inserts. 

So I can't help on the import side, but there are several options for somewhat automated "fixing" the GPX and exporting it to other formats.

**Comment by cyqtmxk** [comment]
> A direct import from a GPX file is not supported. In order to add missing positions you would need to manually insert data into the `positions` table.

Could you please give me some instrucions about how to insert data into the 'positions' table ?
I can't edit the positions table, thank you in advance !
![Image](https://github.com/user-attachments/assets/5ef83f87-8190-46b7-8efc-88e4288ac5d2)
