### ISSUE TITLE
"Health Check Failed" seems to pop up frequently, and vehicle always shows as unlocked

### ISSUE THREAD

**Issue by Zebble** [adriankumpf/teslamate#513]
**Describe the bug**

"Health Check Failed" seems to pop up frequently, and vehicle always shows as unlocked.

**To Reproduce**

Main screen, top right of vehicle info, Health Check Failed is there, along with unlock symbol.

**Expected behavior**

Health Check Failed info would be helpful.  Nothing in documentation as to how to troubleshoot.
When vehicle is locked, the locked symbol should also update.

**Relevant entries from the logs**

No logs during this period...

**Data**

N/A

Data collection appears to be normal.

**Operating environment**

- TeslaMate Version: 1.17.1
- Type of installation: Docker on Synology NAS
- OS: Synology DSM 6.2

**Comment by adriankumpf** [comment]
The health check fails if TeslaMate cannot talk to the Tesla servers, e.g. because of no internet connection or server problems. As a result, the latest data is not available, including whether the car is locked or not.

> Relevant entries from the logs
> 
> No logs during this period...

There are definitely logs for this period. On Synology you might have to check its dedicated Docker UI.

**Comment by Zebble** [comment]
Not sure what happened but it's working fine now.  Got an upgrade from 2020.4.1 to 2020.8.1.1 yesterday.  Not sure if it's related.

Will keep an eye on it!
