### ISSUE TITLE
Make web interface language independent from car language

### ISSUE THREAD

**Issue by joanquro** [adriankumpf/teslamate#582]
I would like to keep English as the language for the web interface regardless of car's language settings (Spanish in my case). Is it possible or is there a workaround to change the language in the web interface?

Thanks!

**Comment by olexs** [comment]
The web interface language isn't dependent on the car, but rather on your browser settings. I have English set as the first and default language in Firefox, and get the interface in English. On my work PC the browser is completely set up with German, and so is the Teslamate UI.

If there is an easy way to add a "force language" switch to the UI so that it ignores the browser preference, that could be useful.

**Comment by joanquro** [comment]
Hello. Thank you for your answer. My car was in English and I changed to Spanish to test some voice commands. When I changed the language in the car the Teslamate UI did the same. I always have Spanish as the language in my browser and never changed to English. That's why I think Teslamate is taking the car language as UI language. I will change the car language back to English and test again.

**Comment by adriankumpf** [comment]
As @olexs said, the language of the web interface depends solely on your browser settings.

An option to overwrite this pre-selected language is planned.
