### ISSUE TITLE
IOS Shortcut to wake teslamate not needed anymore?

### ISSUE THREAD

**Issue by DariBer** [adriankumpf/teslamate#585]
isn't the feature when using the the phone (in this case iPhone) to send to the Teslamate to wakeup or start to get information from the car when the phone is near the car needed anymore?

I can't find the information how to configure the iOS shortcuts in any documentation anymore

**Comment by adriankumpf** [comment]
That's a good question. We are currently between two releases: The next release (v1.19) will come with a proper sleep mode that will eliminate the need to manually resume polling. Therefore the iOS shortcut is no longer needed.

Recently, the old documentation suddenly broke, so I completely revised it. I did not migrate the sleep mode documentation, because it would be removed soon anyway. 

You can find the old docs here: https://teslamate.readthedocs.io/en/v1.18.0/configuration/sleep.html The dev build of v1.19 is also available on DockerHub, if you'd like to beta test it.

**Comment by DariBer** [comment]
So if I use 1.19.0-dev I don't need to use the iOS shortcut?

**Comment by adriankumpf** [comment]
That's right.

**Comment by DariBer** [comment]
great! I'm not so good at Github, I have installed TeslaMate 1.19.0-dev in Docker, how can I see if there's any changes that have been updated so that I can pull the latest Docker version of 1.19 or dev?

**Comment by kongomongo** [comment]
docker-compose pull

**Comment by DariBer** [comment]
yes that's how to update, I wonder if there's a way to see if the docker is updated without pulling :)

**Comment by Rfvgyhn** [comment]
You can view a [list of tags](https://hub.docker.com/r/teslamate/teslamate/tags) on docker hub. It includes when they were last updated. You can also use something like [watchtower](https://github.com/containrrr/watchtower) to automatically update images as well.
