### ISSUE TITLE
Charging_Processes table incomplete

### ISSUE THREAD

**Issue by wavern** [adriankumpf/teslamate#62]
Only start_date, car_id, position_id and address_id are being populated in charging_processes. Everything else is left null.

 The charges table seems to be populating fully. 

I've only started using this but the 3 entries populated so far in charging_processes have the same incomplete entries.

**Comment by adriankumpf** [comment]
What are the logs showing during that period. Are there any errors?

**Comment by wavern** [comment]
This is from just now:
07:39:29.933 [info] Start / :asleep
09:33:10.931 [info] Start / :online
09:33:10.939 [info] Charging / 0.0h left
09:33:32.829 [info] Charging / Restart
09:51:19.626 [info] Charging / Complete

The entry for that in the psql database shows:
"5"	"2019-07-29 09:33:11"										"1"	"330"	"1"

**Comment by adriankumpf** [comment]
I wonder why `Charging / Restart` happened soon after the charging process started. A few questions:

- Do all charging processes show that pattern?
- Was there anything special about that particular charging process (e.g. charge limit exceeded)?
- Are there any successfully logged charging processes?

**Comment by wavern** [comment]
No, Not all charging follows that routine. This is what I have from the logs:

> 07:03:11.172 [info] Charging / 0.0h left
09:33:10.939 [info] Charging / 0.0h left
09:33:32.829 [info] Charging / Restart
09:51:19.626 [info] Charging / Complete
11:28:07.824 [info] Charging / 0.0h left
15:41:10.281 [info] Charging / 0.0h left
15:41:48.466 [info] Charging / Disconnected / 0.0 kWh – 0 min

In fact, the last charging even did actually write correctly to the psql database, however it wasn't a real charging event. I just unplugged at that point and it showed 0kwh added. However at least it worked that time. I'll charge again tonight to see what happens.

**Comment by wavern** [comment]
What's the logic behind when the service will check the state of the car? I set my car up to charge starting at midnight to take advantage of electric rates. Could the car going from full asleep / offline mode to charging cause a hiccup with capturing the charge?

**Comment by adriankumpf** [comment]
> Could the car going from full asleep / offline mode to charging cause a hiccup with capturing the charge?

Okay, yes, that could cause the problem. Also, I think those long charging sessions are an issue right now. I will look into it.

**Comment by wavern** [comment]
This is very strange. From last night's charge:
`03:09:44.902 [info] Start / :asleep
07:00:35.606 [info] Start / :online
07:00:35.618 [info] Charging / 1.83h left
08:41:39.202 [info] Charging / Complete
08:56:49.508 [info] Suspending logging
09:17:59.881 [info] Start / :asleep
`
Looks like it should've caught it all and worked fine, yet it's another mostly empty entry in the charging_process table.

**Comment by adriankumpf** [comment]
Okay, so this is actually intended: the API reports `Charging / Complete` if the charge limit is reached. Only if you stop charging or unplug the charging process will be considered finished.

However, if another `Charging / Restart` should show up while the car is charging that would be a bug.

**Comment by wavern** [comment]
Really? Why not consider it complete if the car says the charging is complete?

I just unplugged my charging cable to see what would happen.

> 16:10:10.924 [warn] Error / :unknown
16:33:44.372 [info] Start / :online

The entry in charging_process still shows mostly nulls.

**Comment by adriankumpf** [comment]
Well, we could do that but if the car charges for a longer period e.g. over night `Complete` does not mean the charging process is actually finished. Every hour or so it will start charging again for a few minutes. Each one of those charging processes would then be logged separately.

> The entry in charging_process still shows mostly nulls.

Okay, this is really strange. Since there was a charging process in progress it should have been completed. Does your car have a stable internet connection when parked?

**Comment by wavern** [comment]
> Well, we could do that but if the car charges for a longer period e.g. over night Complete does not mean the charging process is actually finished. Every hour or so it will start charging again for a few minutes. Each one of those charging processes would then be logged separately.

Could you skip writing to the charging_process if the total wh added was less than a certain threshold? Or ignore a charging start if the remaining time is 0.0h? Am I the only one seeing this issue? My typical use of charging is plug it in when I get home. It'll charge at midnight until it's done and leave it plugged in until I leave. I'd have to imagine that isn't unusual use. 

> Okay, this is really strange. Since there was a charging process in progress it should have been completed. Does your car have a stable internet connection when parked?

Yes, excellent network connection as my primary router is in the room over my garage. 200mbit+ speed tested from inside the car.

**Comment by adriankumpf** [comment]
> Could you skip writing to the charging_process if the total wh added was less than a certain threshold? Or ignore a charging start if the remaining time is 0.0h? Am I the only one seeing this issue? My typical use of charging is plug it in when I get home. It'll charge at midnight until it's done and leave it plugged in until I leave. I'd have to imagine that isn't unusual use.

The downside to this is that the consumption (gross) calculation would then produce slightly wrong results. Let's take a step back – is that really the issue here? To me it looks more like there is this bug you described earlier: when the car is going from asleep / offline mode to charging it somehow does not continue with the charging process and creates a new one instead.

I don't think you're the only one seeing this issue. I just did not run in this bug because in the past I mostly unplugged right after charging.

**Comment by wavern** [comment]
What I mentioned before was meant to be something like this:

- Arrive home after work and plug in, say around 7pm
- Car goes to sleep around 7:30pm
- Car wakes up and immediately starts charging at 12:00am
- Car finishes charging at 2am
- Car goes back to sleep at 2:30am
- I wake the car up at 9am, unplug, go to work.

Are you suggesting that charging should be recorded as starting from 7pm and ending at 9am the next morning in that scenario? Even though it was only actively charging from 12am to 2am? I'm not sure I understand the goal of capturing how long it was plugged in but not charging?

**Comment by adriankumpf** [comment]
Sort of ... in general I would prefer matching the reported state of the API. Based on your example:

* 7pm: either start a charging process or stay in online mode (I don't know yet what the API reports if charging is delayed)
* 7:30pm: car goes to sleep
* 12:00am: (start a charging process if that did not already happen earlier and) start writing data  referencing the charging process into the table `charges`
* 2am: stop writing data into the table `charges` since charging_state is `Complete`
* 2:30am: car goes back to sleep
* 2:30am - 9:00am: if the car wakes up in between to charge a few Wh write data referencing the charging process into the table `charges`
* 9:00am: finish charging process 

There are a few unknowns for me: what happens at 7am and after 2:30am. Depending on that I would prefer recording from 7pm and ending at 9am or from 12am and ending at 2:30am.

Sorry for not fixing it already. I could not yet do a real-world test myself yet.

**Comment by wavern** [comment]
Hey, no need to apologize. You're donating your time here. :)

I have a Sense monitor hooked up to my house power. It shows energy usage realtime and lets me look at graphs of usage in the past. The Tesla wall charger I use is very easy to detect. 11kw/h load whenever it activates. The charger does click on on occasion while connected but no significant load shown when it does.

If you'd like some help debugging this, let me know. I've got a postman profile setup to query everything manually.

**Comment by wavern** [comment]
Last night I did a manual charge for 90mins, starting and stopping it via my phone. It showed up perfectly in the charging_process table and chart. Then at midnight the car woke up from sleep, charged the rest of the way and went back to sleep. That entry was missing bits again. Seems like it's definitely scheduled charges that are an issue.

**Comment by adriankumpf** [comment]
Okay, good to know. Thanks for the info! I'll debug it this weekend.

**Comment by adriankumpf** [comment]
I could finally test and also reproduce it. The fix will be out tomorrow.

**Comment by adriankumpf** [comment]
Release v1.4.3 should fix the issue. Let me know how it goes.

**Comment by wavern** [comment]
> Add migration to fix incomplete charging processes

This part definitely worked. The charging table looks like it's repaired. I'll charge after work tonight and report back on the rest but looks good so far! Thank you. 👍

**Comment by wavern** [comment]
Looks like it worked perfectly! The only thing left that seems amiss is the charge prior to the one last night shows that it took 25 minutes to charge 21kwh giving a charging rate of 50kw/h. That was captured with much older code. I'm thinking you've squashed the bug. :)
