### ISSUE TITLE
Display all consumption figures in Wh/km (or Wh/mi)

### ISSUE THREAD

**Issue by dyxyl** [adriankumpf/teslamate#675]
Various dashboards show consumption in kWh/100km (or kWh/100mi). I would like to see Wh/km (or Wh/mi) either always or as an option in the settings.

Here are some reasons why I think Wh/km is better:
- The car's Energy App displays it in those units.
- The values are shorter (assuming you only need 3 significant figures). The units are shorter too.
- You are less likely to confuse it with energy usage (e.g. Drives has two columns containing values labelled in kWh).
- 100km is not a common unit of length (Who says "I've just driven 0.05 100km to the shops."?).

**Comment by Dulanic** [comment]
I think the biggest issue we have is that we don't have a exact lower level detail as to how much power is used. From my understanding, the data feed via the API doesn't actually give us total power consumption.

The efficiency dashboard has it because we DO have the kWh added back to get back to a certain range so we can calculate the efficiency that charge. AFAIK, the API doesn't have any watts used for a drive am I correct @adriankumpf?

I can think of work arounds to "guess" the wH/mi for each drive... but it won't be super accurate.

**Comment by SDekkers** [comment]
@Dulanic the request is just to change kWh/100km to Wh/km, it's an easy translation; perhaps it should be made configurable ?

**Comment by Dulanic** [comment]
@SDekkers Oh I get it, I was just mumbling /w the fact that we can't quire be super accurate...I might look into adding an option as a PR.
