### ISSUE TITLE
Error 431 on Chrome Browser (Mobile)

### ISSUE THREAD

**Issue by chilman408** [adriankumpf/teslamate#701]
Getting multiple Error 431 on the Chrome Browser (Header too big?) after having to reboot the Teslamate (for unrelated reason).

Clearing cookies in the browser will allow it to connect again.  But if I reboot the Teslamate and try to access localhost:4000 again, the same error appears...and will need to clear cookie again...

Cannot replicate issue on Edge browser or Chrome Mobile browser...but Chrome is the most popular browser out there...

**Describe the bug**

**Expected behavior**

**How to reproduce it (as minimally and precisely as possible)**:

**Relevant entries from the logs**

```
paste logs here
```

**Screenshots**

**Data**

**Environment**

- TeslaMate version:
- Type of installation: Docker or Manual
- OS TeslaMate is installed on:
- User OS & Browser:
- Others:

**Comment by BlaM** [comment]
This error occurs if there are too many/too big cookies. I get it because I have a lot of applications running under the same IP address (just separate ports).

The solution is to clean out the cookies in your browser - for example by going into the Development-Tools (F12) > Application > Cookies

![image](https://user-images.githubusercontent.com/176011/196497453-be279317-250a-4f32-a0e7-7631c8b138b5.png)

If there are many cookies, then clean some out with the DEL key on your keyboard. You may have to log in in other applications if you do that - but it will make TeslaMate accessible again.
