### ISSUE TITLE
add support for alternative database backends (e.g. mysql/mariasql)

### ISSUE THREAD

**Issue by sumnerboy12** [adriankumpf/teslamate#710]
**What would you like to be added**:
Support for MySQL/MariaSQL database storage (as well as PostgreSQL)

**Why is this needed**:
I have an existing MySQL database which I use for Kodi, Icinga, Nextcloud, Traccar, etc, so would prefer not to spin up a new PostgreSQL instance just for teslamate.

**Additional context**:

**Comment by sumnerboy12** [comment]
Is this as simple as switching to https://hexdocs.pm/ecto_sql/Ecto.Adapters.MyXQL.html?

**Comment by Dulanic** [comment]
I doubt this will happen unless someone does a PR. It would need new grafana connectors, updated queries etc...

**Comment by sumnerboy12** [comment]
Thanks @Dulanic, yes it would be a bit of work and more than I can take on currently. Shall I leave this feature request open or close it?

**Comment by Dulanic** [comment]
That's up to you, and it's not my choice. I just have done some PRs and stuff but that's it. BTW, I might recommend moving your stuff to postgres anyways... its better than mysql. I moved my nextcloud and stuff over recently and haven't looked back.

I don't have the time to do it myself. Since I consider postgres superior to mysql, I don't see a big need for it. On a unrelated note.... I hadn't heard of Icinga... I might have to check that out.

**Comment by adriankumpf** [comment]
> I doubt this will happen unless someone does a PR. It would need new grafana connectors, updated queries etc...

Yeah, and we also use posture-specific modules that cannot simply be replaced by mysql. Furthermore, the effort required to support multiple database backends would simply not be feasible in the long run.
