### ISSUE TITLE
Different electricity prices depending on time and day of the week

### ISSUE THREAD

**Issue by KnightwhosayNi777** [adriankumpf/teslamate#772]
**What would you like to be added**: Different electricity prices depending on time and day of the week

**Why is this needed**: Our electricity supplier uses different electricity tariffs depending on the time of day. 

**Additional context**:

**Comment by DrMichael** [comment]
I get more and more the feeling, that that should be covered through a different app.
Teslamate could provide date and time, duration, location and kWh as an export...

**Comment by Dulanic** [comment]
Yeah.... I have the same type of electricity and I just ALWAYS charge at night when it's cheapest. You can always override the cost for those one off situations.  That's a lot of time spent for a tiny use. Wouldn't you always use a set time to start charging? Thats what I do... it doesn't start charging till midnight.

**Comment by petariga** [comment]
It is a nice idea, however for example in our area the timing for different rates is very flexible and changes everyday, so you can't really make some schedule or system which you could put into TeslaMate...

**Comment by baylanger** [comment]
I don't have time this week but I'd like to propose writing a small script that would run via cron.

For the docker image, we add a "cron" pkg.  In the documentations show 1-2 script examples for cases that we know users have asked for and show how to enable their script.

I would go with a bash script but I haven't check all the possibilities that Postgres offers, I'd think for many cases perhaps Postgres would be better.  Comments are welcome :) 

I'll tell you another charge cost case that I'm well aware.  On each day, the cost of the first 40kWh is ~20-25% than above 40kWh.  In this case, a device over mqtt could perhaps report the current total kWh since midnight - otherwise something over http.  This isn't so simple to implement and I'm positive some electric companies likely have even more odd cases.  I know many solar panel owners have devices that work with mqtt, this seems another difficult case for teslamate to calculate real cost... if the sun is out, there's power coming from the panels otherwise it might all be from the electric company.

**Comment by tacotran** [comment]
Whatever solution is discovered here, it will very likely have great use over in https://github.com/adriankumpf/teslamate/issues/655

Or vice-versa.

**Comment by paulobrien** [comment]
We have cheap electricity at night between set hours, so this would be very useful.

**Comment by Dulanic** [comment]
@paulobrien I do also so the easy work around is set your kwh price to your night price. I never charge during peak times, do you?

**Comment by ronnyandre** [comment]
This feature would be awesome. My electricity provider has an excellent API that gives me realtime electricity prices, which would be awesome to implement so I can have real actual charge pricing at home.
