### ISSUE TITLE
MQTT in real time 

### ISSUE THREAD

**Issue by denisjoshua** [adriankumpf/teslamate#793]
First of all I want to thanks a lot for this wonderful script... it's really beautiful !!!  

**What would you like to be added**:
I wish to know if the MQTT topics change in real time when something is happen to Tesla 
For example I put some topics on Node-Red nodes and I lock and unlock the car (in about 30 sec)  
and the topic teslamate/cars/1/locked not receive nothing. 

What I want to ask is how is the timing with TeslaMate please ? 
Is there a loop in some minutes like the Tesla integration in HASS please ? 

**Why is this needed**:
I need to make automation in Node-Red in order to send the photovoltaic current to the Tesla 
when I have too much production. 
So I need to know when the car is pluged in, and if it's already in charge or not. 

Thanks again 
Denis

**Comment by Dulanic** [comment]
@denisjoshua The MQTT is updated anytime the API updates the value. I know this is for sure because I use MQTT /w HASS automation to open my garage door when I get home. This is also why I ensure HASS doesn't record the history and I exclude it from the recorder otherwise your DB grow very large. If you're using MQTT feed, don't use the tesla integration, both would use the API AFAIK.

Just make a sensor like so:
```
- platform: mqtt
  name: tesla_plugged_in
  state_topic: "teslamate/cars/1/plugged_in"
  icon: mdi:power-plug
```

**Comment by denisjoshua** [comment]
I needed Tesla integration from HASSIO cause I must set charge to my Tesla car. 
But noe i discover the Tesla Api node in Node-Red that make just for me...
so I just stop to use the Tesla integration from HASSIO :-)  
Thanks a lot
