### ISSUE TITLE
Enlarge cost per kWh field.

### ISSUE THREAD

**Issue by Dulanic** [adriankumpf/teslamate#805]
Currently, the cost per kWh is stored in numeric(6,2). kWh cost is usually a more precise cost than this. EX: Mine is $0.056705 per kWh.  

Note: Any numeric between 1 and 9 length uses the same amount of bytes. Maybe set it to 9,5?

![PointedWebbedAmericancrocodile 1](https://user-images.githubusercontent.com/2948206/85327394-7dfb4480-b494-11ea-9769-db6d15c9545f.png)

**Comment by adriankumpf** [comment]
It's actually `numeric(6,4)` (cost_per_unit). The structure shown in the screenshot looks outdated? We can of course increase the precision, but at some point the difference is not really noticeable, is it? Especially since the cost per charge is stored as `numeric(6,2)` at the moment. But if 9.5 does not need more space, it makes sense to use it.

**Comment by Dulanic** [comment]
Yeah so in one off charges I agree, but at the aggregate, over the lifetime of the car, it can change it by hundreds of dollars and maybe more for other currencies. I said 9,5 but maybe 9,6 might be better. I couldn't find postgresql docs specified the amount of bytes, I assume it would be similar to T-SQL. I can verify later.

**Comment by Dulanic** [comment]
So I found that this will show you how many bytes. EX: SELECT pg_column_size('11.1111'::numeric(6,4))

Seems psql sizes are slightly diferent that others I have used, I think 6,4 is good. I thought it was 4.2 so I'll go ahead and close this.
