### ISSUE TITLE
Question: TeslaFi/TeslaMate mapping

### ISSUE THREAD

**Issue by Dulanic** [adriankumpf/teslamate#815]
So this isn't a bug, but can you provide a mapping between TeslaFi and Teslamate? The reason I ask is I had a DB failure and it took me a few days to get the old DB recovered. Now I have some duplicate data between 2 backups and manually editing this will be a nightmare.

My best idea is to import all the data to tables without ID's, dedup the data, and then I want to export it to a csv file that I can import back into teslamate.... seems kind of a round about way to do it, but I can't think of a better method.

Unless you have another recommendation?

**Comment by adriankumpf** [comment]
TeslaFi basically exports the raw API data. Only a fraction of this is imported into TeslaMate. It is therefore not so easy to reconstruct that data.

Couldn't you import the most important data (e.g. drives and charges) of the past days manually? It would not be necessary to transfer the entire state history, for example.

**Comment by Dulanic** [comment]
I thought of that, but the id's will be off. So the position drive_id won't match the drives id. Same /w charges.

**Comment by adriankumpf** [comment]
How many drives/charges are we talking about? Couldn't you solve this with a small script that reads the drives and inserts them into the other database (without ID's)? The data from the `positions`/`charges` table could then be migrated with the new ID's.

It would definitely be more time-consuming to first implement a CSV exporter (due to the above mentioned limitations) and then import the whole dataset again :-)

**Comment by Dulanic** [comment]
I'll work on it and see, I'm not the best at scripting :) It isn't much, it's just a few days. I've just got to work out other things like the geofencing etc....

**Comment by Dulanic** [comment]
OK, done that took a while, but it got done. I ended up doing it all in SQL statements because I couldn't figure out how else to do it.
