### ISSUE TITLE
Question - Is there going to be a new release?

### ISSUE THREAD

**Issue by bahree** [adriankumpf/teslamate#894]
I see quite a few PR's and curious on when there would be a new release out? Is there something holding up that we can help with? Thanks.

**Comment by DrMichael** [comment]
Perhaps waiting for Grafana 7.2? With some necessary bug fixes for tables?

**Comment by adriankumpf** [comment]
I will not give a release date, because a release is a lot of work. But it is planned soon™, latest when Grafana 7.2 is out. 

Yes, you can help with testing :-) There is an "edge" tag available on DockerHub, which always corresponds to the latest development version, and is updated with each commit to master.

**Comment by fatbasstard** [comment]
@adriankumpf The Table is just got pushed to Grafana 7.3...

**Comment by petariga** [comment]
It looks like that if it goes this way, there won’t be any release of 1.20.0 anytime soon...

**Comment by detritu5** [comment]
Any news??? How can we update the container to the edge version?? I usually make 
docker-compose pull
docker-compose up --build -d

But not idea to update to the edge version

**Comment by adriankumpf** [comment]
Alright, going to close this now that _v1.20_ is out.
