### ISSUE TITLE
Error 401 on Tesla car

### ISSUE THREAD

**Issue by carp8000** [adriankumpf/teslamate#905]
Hi,

I'm able to acces Teslamate via google chrome and get prompted to use password.

But in my car I get acces dinied. Did a hard reset of the car - tried shifting Tesla password as well. Any idea what I'm doing wrong?

Also data are missing in Grafana as if it doesn't pull all data like energy consumption.

**Comment by olexs** [comment]
The Tesla browser does not support basic auth. You need a more advanced authentication mechanism if you want to use Teslamate in the car.

**Comment by carp8000** [comment]
Any suggestions on how to fix it?

**Comment by olexs** [comment]
You either need to remove the "basic auth" middleware from your TeslaMate setup (**warning: not recommended**, since it leaves your TeslaMate instance open to anyone knowing the URL), or you need to use an external auth provider with ForwardAuth middleware for Traefik. The latter is a bit complicated, depending on which provider you choose to use and how much experience with Traefik you have.

Do you really need access to TeslaMate from the car's browser? There is not much info you can see there that the car itself doesn't already show. And to check if it's working or not, I find it easier to pull it up on my phone, where BasicAuth works just fine.

**Comment by Dulanic** [comment]
I've never tried it, but I wonder if the in car browser would support it if passed via the URL? aka https://user:pw@teslamate.domain.com

**Comment by olexs** [comment]
Just tested it in my Model 3, it works! Thanks for the idea @Dulanic. 

The only issue is that you can see the password in plaintext in the URL bar and in the bookmark list if you bookmark it, but I guess it's a compromise.
