### ISSUE TITLE
What is the geo-fence feature for?

### ISSUE THREAD

**Issue by traviscollins** [adriankumpf/teslamate#97]
I poked around the documentation, but found no explanation for why one might use the Geo-Fences feature.

**Comment by adriankumpf** [comment]
At the moment it is only a way to create custom locations like "Home" or "Work". It is particularly useful if the addresses provided by [OSM](https://www.openstreetmap.org) in a region are inaccurate.

**Comment by olexs** [comment]
Should this be documented in the readme? I assume it could be useful info for new users that they can created such custom locations, e.g. if they street-park at home or at work where the exact location/address may wary.

Also, suggestion: "use current/last known location" for coordinates of a new geo-fence location, instead of always requiring manual entry. Picking from a map would be awesome as well, though I assume that's more complicated to build that it is worth.

**Comment by adriankumpf** [comment]
> Should this be documented in the readme? I assume it could be useful info for new users that they can create such custom locations, e.g. if they street-park at home or at work where the exact location/address may vary.

I thought it's self-explanatory but you're right, I'll  document it.

> Also, suggestion: "use current/last known location" for coordinates of a new geo-fence location, instead of always requiring manual entry. Picking from a map would be awesome as well, though I assume that's more complicated to build that it is worth.

Yeah, that would be very convenient. I'll add it to the roadmap. But it's not a priority right now.
